-- ============================================================
-- APPLY SUBCONTRACTORS MASTER + 119-SUB SEED (one paste)
-- Generated 2026-08-04. Run once in the Supabase SQL editor.
-- ============================================================

-- ===========================================================================
-- subcontractors — the curated MASTER directory (system of record) that powers
-- the Value Engine: "a reliable number anywhere in NC, and we commit to build it."
--
-- This is the queryable directory the matching engine reads. It is distinct from
-- public.subcontractor_applications (raw INBOUND intake from the /partners form):
--   subcontractor_applications = raw applicants  →  (approve)  →  subcontractors master
-- Sourced subs (scraped/licensing-board/permit records) land here directly with
-- source = 'sourced-import' and status = 'new'.
--
-- Canonical enums are kept in sync with sc-platform/lib/vendors.ts:
--   NC_REGIONS (7)  and  COMMON_TRADES (18)  and  V_STATUSES (new|vetting|approved|bench|declined)
-- Regions live in a text[] (multi-coverage) with a GIN index, matching vendors.ts `regions text[]`.
-- Granular market pricing joins via public.market_tiers (ZIP-prefix → tier + multiplier).
--
-- Idempotent: safe to re-run. Apply in the Supabase SQL editor, THEN run
-- subcontractors_import.sql to load the 119-sub seed.
-- ===========================================================================

create table if not exists public.subcontractors (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  -- identity
  company_name text not null,
  contact_name text,
  email text,
  phone text,
  website text,

  -- classification
  trade text not null,                 -- canonical COMMON_TRADES value
  source_trade text,                   -- raw trade label from the source (provenance)
  specialties text,
  regions text[],                      -- canonical NC_REGIONS values (multi-coverage)
  source_service_area text,            -- raw free-text coverage from the source
  home_base_city text,

  -- vetting
  license_type text,
  license_number text,
  license_state text default 'NC',
  license_verified boolean not null default false,   -- verified against the state board roster
  license_expiry date,
  insurance_carrier text,
  insurance_limits text,
  insurance_expiry date,
  coi_on_file boolean not null default false,
  workers_comp text,
  crew_size text,
  years_in_business text,

  -- performance
  rating numeric,                      -- 0–5
  jobs_completed integer not null default 0,
  jobs_successful integer not null default 0,
  reliability_score numeric,           -- computed or manual

  -- availability  (structured — did not exist anywhere before)
  availability_status text not null default 'unknown'
    check (availability_status in ('available','limited','booked','unknown')),
  available_from date,
  availability_confirmed_at timestamptz,

  -- pricing  (rate-card summary here; line-item history in sub_quotes)
  pricing_tier text,                   -- e.g. budget / mid / premium, or A/B/C
  rate_notes text,

  -- lifecycle / provenance
  status text not null default 'new'
    check (status in ('new','vetting','approved','bench','declined')),
  source text not null default 'manual',   -- sourced-import | inbound-application | referral | manual
  source_application_id bigint references public.subcontractor_applications (id),
  review_notes text,
  reviewer_email text,
  approved_at timestamptz,
  notes text
);

-- Dedupe key: one master row per company per canonical trade.
create unique index if not exists subcontractors_company_trade_uniq
  on public.subcontractors (lower(company_name), trade);

create index if not exists subcontractors_trade_idx on public.subcontractors (trade);
create index if not exists subcontractors_status_idx on public.subcontractors (status);
create index if not exists subcontractors_availability_idx on public.subcontractors (availability_status);
create index if not exists subcontractors_regions_gin on public.subcontractors using gin (regions);

-- ---------------------------------------------------------------------------
-- sub_quotes — historical line-item quotes. Every quote collected becomes
-- future pricing intelligence the matching engine can price a deal from.
-- ---------------------------------------------------------------------------
create table if not exists public.sub_quotes (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  subcontractor_id uuid not null references public.subcontractors (id) on delete cascade,
  deal_ref text,                       -- optional link to a property/deal
  trade text,
  line_item text,
  scope_description text,
  unit text,                           -- ea | sf | lf | ls
  quantity numeric,
  unit_price numeric,
  total_amount numeric,
  region text,                         -- canonical NC_REGIONS value
  market_zip_prefix text,              -- joins public.market_tiers.zip_prefix
  quoted_at date,
  won boolean,                         -- did we use this quote / did the work happen
  notes text
);

create index if not exists sub_quotes_subcontractor_idx on public.sub_quotes (subcontractor_id);
create index if not exists sub_quotes_trade_idx on public.sub_quotes (trade);
create index if not exists sub_quotes_region_idx on public.sub_quotes (region);

-- ---------------------------------------------------------------------------
-- updated_at touch trigger (mirrors market_tiers convention)
-- ---------------------------------------------------------------------------
create or replace function public.touch_subcontractors_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists subcontractors_touch_updated_at on public.subcontractors;
create trigger subcontractors_touch_updated_at
before update on public.subcontractors
for each row execute function public.touch_subcontractors_updated_at();

-- RLS: service role only (matches market_tiers / estimate_rules — server-side reads).
alter table public.subcontractors enable row level security;
alter table public.sub_quotes enable row level security;


-- Generated by build_subcontractors_import.py — 119-sub seed for public.subcontractors
-- Apply subcontractors_master.sql FIRST. Idempotent via ON CONFLICT (lower(company_name), trade).

insert into public.subcontractors (company_name, contact_name, email, phone, website, trade, source_trade, specialties, regions, source_service_area, home_base_city, license_number, notes, source, status, license_verified, availability_status) values ('C-Phase Electric', NULL, NULL, '910-622-0742', 'https://c-phaseelectric.com/', 'Electrical', 'Electrician', 'Residential, Commercial, Industrial', ARRAY['Eastern NC']::text[], 'New Bern area', 'New Bern', NULL, NULL, 'sourced-import', 'new', false, 'unknown') on conflict (lower(company_name), trade) do nothing;
insert into public.subcontractors (company_name, contact_name, email, phone, website, trade, source_trade, specialties, regions, source_service_area, home_base_city, license_number, notes, source, status, license_verified, availability_status) values ('McMillan Renovations & Electrical', NULL, NULL, NULL, 'https://mcmillanrenovations.com/', 'Electrical', 'Electrician', 'Residential, Commercial', ARRAY['Eastern NC']::text[], 'New Bern area', 'New Bern', NULL, NULL, 'sourced-import', 'new', false, 'unknown') on conflict (lower(company_name), trade) do nothing;
insert into public.subcontractors (company_name, contact_name, email, phone, website, trade, source_trade, specialties, regions, source_service_area, home_base_city, license_number, notes, source, status, license_verified, availability_status) values ('JRB Electric / DR Electric', NULL, NULL, '252-617-5900', 'https://www.drelectricnc.com/', 'Electrical', 'Electrician', 'Residential, Commercial', ARRAY['Eastern NC']::text[], 'New Bern area', 'New Bern', NULL, NULL, 'sourced-import', 'new', false, 'unknown') on conflict (lower(company_name), trade) do nothing;
insert into public.subcontractors (company_name, contact_name, email, phone, website, trade, source_trade, specialties, regions, source_service_area, home_base_city, license_number, notes, source, status, license_verified, availability_status) values ('R Brown Electric Service', NULL, NULL, NULL, 'https://www.rbrownelectricservice.com/', 'Electrical', 'Electrician', 'Residential, Commercial, Industrial', ARRAY['Eastern NC']::text[], 'New Bern area', 'New Bern', NULL, NULL, 'sourced-import', 'new', false, 'unknown') on conflict (lower(company_name), trade) do nothing;
insert into public.subcontractors (company_name, contact_name, email, phone, website, trade, source_trade, specialties, regions, source_service_area, home_base_city, license_number, notes, source, status, license_verified, availability_status) values ('Whiting Electrical Services', NULL, NULL, '252-576-6105', 'https://whitingelectricalservices.com/locations/new-bern-nc/', 'Electrical', 'Electrician', 'Residential, Commercial', ARRAY['Eastern NC']::text[], 'New Bern and 50-mile radius', 'New Bern', NULL, NULL, 'sourced-import', 'new', false, 'unknown') on conflict (lower(company_name), trade) do nothing;
insert into public.subcontractors (company_name, contact_name, email, phone, website, trade, source_trade, specialties, regions, source_service_area, home_base_city, license_number, notes, source, status, license_verified, availability_status) values ('Eastern Electrical Corp', NULL, NULL, '252-541-4400', 'https://www.easternelectricalcorp.com/greenville-nc/', 'Electrical', 'Electrician', 'Residential, Commercial', ARRAY['Eastern NC']::text[], 'Greenville area', 'Greenville', NULL, NULL, 'sourced-import', 'new', false, 'unknown') on conflict (lower(company_name), trade) do nothing;
insert into public.subcontractors (company_name, contact_name, email, phone, website, trade, source_trade, specialties, regions, source_service_area, home_base_city, license_number, notes, source, status, license_verified, availability_status) values ('Hemby''s Electrical Service', 'Todd Hemby', 'hembyelec@aol.com', '252-355-2488', 'https://hembyselectricalservice.com/', 'Electrical', 'Electrician', 'Residential, Commercial, Agricultural, Industrial', ARRAY['Eastern NC']::text[], 'Greenville, Pitt County area', 'Greenville', NULL, NULL, 'sourced-import', 'new', false, 'unknown') on conflict (lower(company_name), trade) do nothing;
insert into public.subcontractors (company_name, contact_name, email, phone, website, trade, source_trade, specialties, regions, source_service_area, home_base_city, license_number, notes, source, status, license_verified, availability_status) values ('Bitting Electric', NULL, NULL, '919-467-9417', 'https://www.bittingelectric.com/areas-we-serve/greenville/', 'Electrical', 'Electrician', 'Commercial, Generator Installation', ARRAY['Eastern NC']::text[], 'Greenville, Winterville, Farmville, Wilson', 'Greenville', NULL, NULL, 'sourced-import', 'new', false, 'unknown') on conflict (lower(company_name), trade) do nothing;
insert into public.subcontractors (company_name, contact_name, email, phone, website, trade, source_trade, specialties, regions, source_service_area, home_base_city, license_number, notes, source, status, license_verified, availability_status) values ('Whiting Electrical Services', NULL, NULL, '252-576-6105', 'https://whitingelectricalservices.com/', 'Electrical', 'Electrician', 'Residential, Commercial', ARRAY['Eastern NC']::text[], 'Greenville and 50-mile radius', 'Greenville', NULL, NULL, 'sourced-import', 'new', false, 'unknown') on conflict (lower(company_name), trade) do nothing;
insert into public.subcontractors (company_name, contact_name, email, phone, website, trade, source_trade, specialties, regions, source_service_area, home_base_city, license_number, notes, source, status, license_verified, availability_status) values ('Wheeler Electrical Company', NULL, NULL, NULL, 'https://www.wheelerelectricalinc.com/greenville-nc', 'Electrical', 'Electrician', 'Residential, Commercial', ARRAY['Eastern NC']::text[], 'Greenville area', 'Greenville', NULL, NULL, 'sourced-import', 'new', false, 'unknown') on conflict (lower(company_name), trade) do nothing;
insert into public.subcontractors (company_name, contact_name, email, phone, website, trade, source_trade, specialties, regions, source_service_area, home_base_city, license_number, notes, source, status, license_verified, availability_status) values ('Kight Electric', NULL, NULL, NULL, NULL, 'Electrical', 'Electrician', 'Residential, Commercial', ARRAY['Eastern NC']::text[], 'Elizabeth City area', 'Elizabeth City', NULL, NULL, 'sourced-import', 'new', false, 'unknown') on conflict (lower(company_name), trade) do nothing;
insert into public.subcontractors (company_name, contact_name, email, phone, website, trade, source_trade, specialties, regions, source_service_area, home_base_city, license_number, notes, source, status, license_verified, availability_status) values ('B & M Contractors', NULL, NULL, NULL, NULL, 'Electrical', 'Electrician', 'Residential, Commercial', ARRAY['Eastern NC']::text[], 'Elizabeth City area', 'Elizabeth City', NULL, NULL, 'sourced-import', 'new', false, 'unknown') on conflict (lower(company_name), trade) do nothing;
insert into public.subcontractors (company_name, contact_name, email, phone, website, trade, source_trade, specialties, regions, source_service_area, home_base_city, license_number, notes, source, status, license_verified, availability_status) values ('Abraham''s Electric', NULL, NULL, '252-331-3088', NULL, 'Electrical', 'Electrician', 'Residential, Commercial, Church', ARRAY['Eastern NC']::text[], 'Elizabeth City area', 'Elizabeth City', NULL, NULL, 'sourced-import', 'new', false, 'unknown') on conflict (lower(company_name), trade) do nothing;
insert into public.subcontractors (company_name, contact_name, email, phone, website, trade, source_trade, specialties, regions, source_service_area, home_base_city, license_number, notes, source, status, license_verified, availability_status) values ('Angel Advanced Technologies', NULL, NULL, NULL, 'https://www.angeladvancedtech.com/elizabeth-city/', 'Electrical', 'Electrician', 'Residential, Commercial', ARRAY['Eastern NC']::text[], 'Elizabeth City and surrounding', 'Elizabeth City', NULL, NULL, 'sourced-import', 'new', false, 'unknown') on conflict (lower(company_name), trade) do nothing;
insert into public.subcontractors (company_name, contact_name, email, phone, website, trade, source_trade, specialties, regions, source_service_area, home_base_city, license_number, notes, source, status, license_verified, availability_status) values ('Crowe Electrical Services', NULL, NULL, NULL, 'https://croweelectrical.com/', 'Electrical', 'Electrician', 'Residential, Commercial', ARRAY['Charlotte Metro']::text[], 'Conover, Granite Falls, Hickory, Lenoir, Morganton, Newton', 'Hickory', NULL, NULL, 'sourced-import', 'new', false, 'unknown') on conflict (lower(company_name), trade) do nothing;
insert into public.subcontractors (company_name, contact_name, email, phone, website, trade, source_trade, specialties, regions, source_service_area, home_base_city, license_number, notes, source, status, license_verified, availability_status) values ('Lake James Electric LLC', NULL, NULL, NULL, 'https://lakejameselectric.com/', 'Electrical', 'Electrician', 'Residential, Commercial', ARRAY['Charlotte Metro', 'Western NC (Asheville)']::text[], 'Morganton, Hickory, Lenoir, Western NC', 'Morganton', NULL, NULL, 'sourced-import', 'new', false, 'unknown') on conflict (lower(company_name), trade) do nothing;
insert into public.subcontractors (company_name, contact_name, email, phone, website, trade, source_trade, specialties, regions, source_service_area, home_base_city, license_number, notes, source, status, license_verified, availability_status) values ('Lake Electric Co. Inc.', NULL, NULL, NULL, 'https://lakeelectric.com/', 'Electrical', 'Electrician', 'Residential, Commercial, Industrial', ARRAY['Charlotte Metro']::text[], 'Hickory, Lenoir, Morganton, Gastonia, Statesville, Charlotte', 'Hickory', NULL, NULL, 'sourced-import', 'new', false, 'unknown') on conflict (lower(company_name), trade) do nothing;
insert into public.subcontractors (company_name, contact_name, email, phone, website, trade, source_trade, specialties, regions, source_service_area, home_base_city, license_number, notes, source, status, license_verified, availability_status) values ('Triangle Contractors', NULL, NULL, '828-432-0025', 'https://triangle-contractors.com/', 'Electrical', 'Electrician', 'Residential, Commercial', ARRAY['Charlotte Metro']::text[], 'Morganton, Mooresville area', 'Morganton', NULL, NULL, 'sourced-import', 'new', false, 'unknown') on conflict (lower(company_name), trade) do nothing;
insert into public.subcontractors (company_name, contact_name, email, phone, website, trade, source_trade, specialties, regions, source_service_area, home_base_city, license_number, notes, source, status, license_verified, availability_status) values ('Bates Electric', NULL, NULL, '704-741-4919', 'https://bates-electric.com/locations/charlotte-nc/', 'Electrical', 'Electrician', 'Residential, Commercial', ARRAY['Charlotte Metro']::text[], 'Charlotte metro', 'Charlotte', NULL, NULL, 'sourced-import', 'new', false, 'unknown') on conflict (lower(company_name), trade) do nothing;
insert into public.subcontractors (company_name, contact_name, email, phone, website, trade, source_trade, specialties, regions, source_service_area, home_base_city, license_number, notes, source, status, license_verified, availability_status) values ('On Time Electrical', NULL, NULL, '980-256-3854', 'https://www.itselectriccharlotte.com/', 'Electrical', 'Electrician', 'Residential, Commercial', ARRAY['Charlotte Metro']::text[], 'Charlotte metro', 'Charlotte', NULL, NULL, 'sourced-import', 'new', false, 'unknown') on conflict (lower(company_name), trade) do nothing;
insert into public.subcontractors (company_name, contact_name, email, phone, website, trade, source_trade, specialties, regions, source_service_area, home_base_city, license_number, notes, source, status, license_verified, availability_status) values ('David Long Electrical', NULL, 'pjames@davidlongelectrical.com', '704-849-0007', 'https://www.davidlongelectrical.com/', 'Electrical', 'Electrician', 'Residential, Commercial', ARRAY['Charlotte Metro']::text[], 'Charlotte and surrounding counties', 'Charlotte', NULL, NULL, 'sourced-import', 'new', false, 'unknown') on conflict (lower(company_name), trade) do nothing;
insert into public.subcontractors (company_name, contact_name, email, phone, website, trade, source_trade, specialties, regions, source_service_area, home_base_city, license_number, notes, source, status, license_verified, availability_status) values ('Ace Electric', NULL, 'nsk@ace-electric.com', '704-527-6464', 'https://ace-electric.com/', 'Electrical', 'Electrician', 'Residential, Commercial', ARRAY['Charlotte Metro']::text[], 'Charlotte and surrounding', 'Charlotte', NULL, NULL, 'sourced-import', 'new', false, 'unknown') on conflict (lower(company_name), trade) do nothing;
insert into public.subcontractors (company_name, contact_name, email, phone, website, trade, source_trade, specialties, regions, source_service_area, home_base_city, license_number, notes, source, status, license_verified, availability_status) values ('Ewing Electric', NULL, NULL, '704-804-3320', 'https://ewingelectricco.com/', 'Electrical', 'Electrician', 'Residential, Commercial', ARRAY['Charlotte Metro']::text[], 'Charlotte metro', 'Charlotte', NULL, NULL, 'sourced-import', 'new', false, 'unknown') on conflict (lower(company_name), trade) do nothing;
insert into public.subcontractors (company_name, contact_name, email, phone, website, trade, source_trade, specialties, regions, source_service_area, home_base_city, license_number, notes, source, status, license_verified, availability_status) values ('Scott Plumbing & Heating', NULL, NULL, NULL, 'https://www.scottph.com/', 'Mechanical / HVAC', 'HVAC', 'Residential, Commercial', ARRAY['Eastern NC']::text[], 'New Bern area', 'New Bern', NULL, NULL, 'sourced-import', 'new', false, 'unknown') on conflict (lower(company_name), trade) do nothing;
insert into public.subcontractors (company_name, contact_name, email, phone, website, trade, source_trade, specialties, regions, source_service_area, home_base_city, license_number, notes, source, status, license_verified, availability_status) values ('Dixon Heating & Air Conditioning', NULL, NULL, NULL, 'https://dixonheatingandair.com/', 'Mechanical / HVAC', 'HVAC', 'Residential, Commercial', ARRAY['Eastern NC']::text[], 'New Bern area', 'New Bern', NULL, NULL, 'sourced-import', 'new', false, 'unknown') on conflict (lower(company_name), trade) do nothing;
insert into public.subcontractors (company_name, contact_name, email, phone, website, trade, source_trade, specialties, regions, source_service_area, home_base_city, license_number, notes, source, status, license_verified, availability_status) values ('Comfort Air of New Bern', NULL, NULL, NULL, 'https://comfortair-newbern.com/', 'Mechanical / HVAC', 'HVAC', 'Residential, Commercial', ARRAY['Eastern NC']::text[], 'New Bern area', 'New Bern', NULL, NULL, 'sourced-import', 'new', false, 'unknown') on conflict (lower(company_name), trade) do nothing;
insert into public.subcontractors (company_name, contact_name, email, phone, website, trade, source_trade, specialties, regions, source_service_area, home_base_city, license_number, notes, source, status, license_verified, availability_status) values ('Coastal Carolina Air Conditioning', NULL, NULL, NULL, 'https://www.coastalcarolinaairconditioning.com/', 'Mechanical / HVAC', 'HVAC', 'Residential, Commercial', ARRAY['Eastern NC']::text[], 'New Bern area', 'New Bern', NULL, NULL, 'sourced-import', 'new', false, 'unknown') on conflict (lower(company_name), trade) do nothing;
insert into public.subcontractors (company_name, contact_name, email, phone, website, trade, source_trade, specialties, regions, source_service_area, home_base_city, license_number, notes, source, status, license_verified, availability_status) values ('Airtech Mechanical Services', NULL, NULL, NULL, 'https://www.airtechnc.com/', 'Mechanical / HVAC', 'HVAC', 'Residential, Commercial', ARRAY['Eastern NC']::text[], 'New Bern area', 'New Bern', NULL, NULL, 'sourced-import', 'new', false, 'unknown') on conflict (lower(company_name), trade) do nothing;
insert into public.subcontractors (company_name, contact_name, email, phone, website, trade, source_trade, specialties, regions, source_service_area, home_base_city, license_number, notes, source, status, license_verified, availability_status) values ('Diaz Framing & Painting', NULL, NULL, NULL, 'https://diazframingandpaintingnc.com/', 'General / Framing', 'Framer', 'Residential, Commercial', ARRAY['Eastern NC']::text[], 'Greenville area', 'Greenville', NULL, NULL, 'sourced-import', 'new', false, 'unknown') on conflict (lower(company_name), trade) do nothing;
insert into public.subcontractors (company_name, contact_name, email, phone, website, trade, source_trade, specialties, regions, source_service_area, home_base_city, license_number, notes, source, status, license_verified, availability_status) values ('D&E Developments LLC', 'Dwayne Brabble', NULL, '252-638-8223', 'https://www.dedevelopments.com', 'General / Framing', 'Framer', 'Commercial, Residential', ARRAY['Eastern NC']::text[], 'New Bern area', 'New Bern', NULL, NULL, 'sourced-import', 'new', false, 'unknown') on conflict (lower(company_name), trade) do nothing;
insert into public.subcontractors (company_name, contact_name, email, phone, website, trade, source_trade, specialties, regions, source_service_area, home_base_city, license_number, notes, source, status, license_verified, availability_status) values ('Advanced Framing', NULL, NULL, NULL, 'https://www.advancedframinggroup.com/', 'General / Framing', 'Framer', 'Residential, Commercial', NULL, 'North Carolina, South Carolina', 'Regional', NULL, '[region unmapped — set NC_REGIONS in VendorBoard]', 'sourced-import', 'new', false, 'unknown') on conflict (lower(company_name), trade) do nothing;
insert into public.subcontractors (company_name, contact_name, email, phone, website, trade, source_trade, specialties, regions, source_service_area, home_base_city, license_number, notes, source, status, license_verified, availability_status) values ('Residential Land Services PLLC', NULL, NULL, NULL, 'https://www.rls-nc.com/', 'Other', 'Surveyor', 'Residential, Commercial', ARRAY['Charlotte Metro', 'Triangle (Raleigh–Durham)', 'Triad (Greensboro–Winston-Salem)', 'Fayetteville / Sandhills', 'Wilmington / Coastal', 'Eastern NC', 'Western NC (Asheville)']::text[], 'Raleigh and statewide', 'Raleigh', NULL, '[source trade: Surveyor — mapped to Other; reclassify]', 'sourced-import', 'new', false, 'unknown') on conflict (lower(company_name), trade) do nothing;
insert into public.subcontractors (company_name, contact_name, email, phone, website, trade, source_trade, specialties, regions, source_service_area, home_base_city, license_number, notes, source, status, license_verified, availability_status) values ('Charlotte Surveyor Group', NULL, NULL, '704-259-7575', 'https://charlottelandsurveys.com/', 'Other', 'Surveyor', 'Residential, Commercial', ARRAY['Charlotte Metro']::text[], 'Charlotte metro', 'Charlotte', NULL, '[source trade: Surveyor — mapped to Other; reclassify]', 'sourced-import', 'new', false, 'unknown') on conflict (lower(company_name), trade) do nothing;
insert into public.subcontractors (company_name, contact_name, email, phone, website, trade, source_trade, specialties, regions, source_service_area, home_base_city, license_number, notes, source, status, license_verified, availability_status) values ('Atlas Surveying CLT', NULL, NULL, '980-949-8475', 'https://www.atlassurveying.com/', 'Other', 'Surveyor', 'Residential, Commercial', ARRAY['Charlotte Metro']::text[], 'Charlotte area', 'Charlotte', NULL, '[source trade: Surveyor — mapped to Other; reclassify]', 'sourced-import', 'new', false, 'unknown') on conflict (lower(company_name), trade) do nothing;
insert into public.subcontractors (company_name, contact_name, email, phone, website, trade, source_trade, specialties, regions, source_service_area, home_base_city, license_number, notes, source, status, license_verified, availability_status) values ('Joseph C Roberts Land Surveying', NULL, NULL, NULL, 'https://josephcrobertslandsurveying.com/', 'Other', 'Surveyor', 'Residential, Commercial, Boundary', ARRAY['Charlotte Metro']::text[], 'Charlotte area', 'Charlotte', NULL, '[source trade: Surveyor — mapped to Other; reclassify]', 'sourced-import', 'new', false, 'unknown') on conflict (lower(company_name), trade) do nothing;
insert into public.subcontractors (company_name, contact_name, email, phone, website, trade, source_trade, specialties, regions, source_service_area, home_base_city, license_number, notes, source, status, license_verified, availability_status) values ('Charlotte Land Surveyor', NULL, NULL, '704-285-1222', 'https://charlottelandsurveyor.com/', 'Other', 'Surveyor', 'Residential, Commercial', ARRAY['Charlotte Metro']::text[], 'Charlotte metro', 'Charlotte', NULL, '[source trade: Surveyor — mapped to Other; reclassify]', 'sourced-import', 'new', false, 'unknown') on conflict (lower(company_name), trade) do nothing;
insert into public.subcontractors (company_name, contact_name, email, phone, website, trade, source_trade, specialties, regions, source_service_area, home_base_city, license_number, notes, source, status, license_verified, availability_status) values ('Newcomb Land Surveyors PLLC', NULL, NULL, NULL, 'https://nls-nc.com/', 'Other', 'Surveyor', 'Residential, Commercial', ARRAY['Wilmington / Coastal', 'Triangle (Raleigh–Durham)']::text[], 'Raleigh, Piedmont, Coastal NC', 'Raleigh', NULL, '[source trade: Surveyor — mapped to Other; reclassify]', 'sourced-import', 'new', false, 'unknown') on conflict (lower(company_name), trade) do nothing;
insert into public.subcontractors (company_name, contact_name, email, phone, website, trade, source_trade, specialties, regions, source_service_area, home_base_city, license_number, notes, source, status, license_verified, availability_status) values ('Boundary Zone', NULL, NULL, NULL, 'https://boundaryzone.com/north-carolina-offices/', 'Other', 'Surveyor', 'Residential, Commercial', ARRAY['Triangle (Raleigh–Durham)', 'Charlotte Metro']::text[], 'Raleigh, Charlotte area', 'Raleigh', NULL, '[source trade: Surveyor — mapped to Other; reclassify]', 'sourced-import', 'new', false, 'unknown') on conflict (lower(company_name), trade) do nothing;
insert into public.subcontractors (company_name, contact_name, email, phone, website, trade, source_trade, specialties, regions, source_service_area, home_base_city, license_number, notes, source, status, license_verified, availability_status) values ('ACM Design Architects', NULL, NULL, NULL, 'https://www.acmdesignarchitects.com/', 'Other', 'Architect', 'Residential custom homes, renovations', ARRAY['Western NC (Asheville)']::text[], 'Asheville area', 'Asheville', NULL, '[source trade: Architect — mapped to Other; reclassify]', 'sourced-import', 'new', false, 'unknown') on conflict (lower(company_name), trade) do nothing;
insert into public.subcontractors (company_name, contact_name, email, phone, website, trade, source_trade, specialties, regions, source_service_area, home_base_city, license_number, notes, source, status, license_verified, availability_status) values ('Altura Architects', NULL, NULL, NULL, 'https://alturaarchitects.com/', 'Other', 'Architect', 'Residential, Commercial', NULL, 'Western North Carolina', 'Asheville', NULL, '[source trade: Architect — mapped to Other; reclassify] [region unmapped — set NC_REGIONS in VendorBoard]', 'sourced-import', 'new', false, 'unknown') on conflict (lower(company_name), trade) do nothing;
insert into public.subcontractors (company_name, contact_name, email, phone, website, trade, source_trade, specialties, regions, source_service_area, home_base_city, license_number, notes, source, status, license_verified, availability_status) values ('Andrew A. Willett Architect PA', NULL, NULL, '828-337-7639', 'https://awillettarchitect.com/', 'Other', 'Architect', 'Residential custom homes, renovations', ARRAY['Western NC (Asheville)']::text[], 'Asheville area', 'Asheville', NULL, '[source trade: Architect — mapped to Other; reclassify]', 'sourced-import', 'new', false, 'unknown') on conflict (lower(company_name), trade) do nothing;
insert into public.subcontractors (company_name, contact_name, email, phone, website, trade, source_trade, specialties, regions, source_service_area, home_base_city, license_number, notes, source, status, license_verified, availability_status) values ('Assembly Architecture & Build', NULL, NULL, NULL, 'https://www.assemblyab.com/', 'Other', 'Architect', 'Residential design-build', ARRAY['Western NC (Asheville)']::text[], 'Asheville area', 'Asheville', NULL, '[source trade: Architect — mapped to Other; reclassify]', 'sourced-import', 'new', false, 'unknown') on conflict (lower(company_name), trade) do nothing;
insert into public.subcontractors (company_name, contact_name, email, phone, website, trade, source_trade, specialties, regions, source_service_area, home_base_city, license_number, notes, source, status, license_verified, availability_status) values ('Carlton Edwards Architects', 'Rob Carlton', NULL, NULL, 'https://carlton-edwards.com/asheville/', 'Other', 'Architect', 'Residential, Commercial, Sustainable design', ARRAY['Western NC (Asheville)']::text[], 'Asheville area', 'Asheville', NULL, '[source trade: Architect — mapped to Other; reclassify]', 'sourced-import', 'new', false, 'unknown') on conflict (lower(company_name), trade) do nothing;
insert into public.subcontractors (company_name, contact_name, email, phone, website, trade, source_trade, specialties, regions, source_service_area, home_base_city, license_number, notes, source, status, license_verified, availability_status) values ('Griffin Architects PA', NULL, NULL, NULL, 'https://www.griffinarchitectspa.com/', 'Other', 'Architect', 'Residential, Commercial, Historic preservation', ARRAY['Western NC (Asheville)']::text[], 'Western NC', 'Asheville', NULL, '[source trade: Architect — mapped to Other; reclassify]', 'sourced-import', 'new', false, 'unknown') on conflict (lower(company_name), trade) do nothing;
insert into public.subcontractors (company_name, contact_name, email, phone, website, trade, source_trade, specialties, regions, source_service_area, home_base_city, license_number, notes, source, status, license_verified, availability_status) values ('Unified Studio Architect', NULL, NULL, NULL, 'https://unifiedstudioarchitect.com/north-carolina-architecture-services/', 'Other', 'Architect', 'Residential, Commercial', ARRAY['Charlotte Metro', 'Triangle (Raleigh–Durham)', 'Triad (Greensboro–Winston-Salem)', 'Fayetteville / Sandhills', 'Wilmington / Coastal', 'Eastern NC', 'Western NC (Asheville)']::text[], 'Statewide NC', 'Regional', NULL, '[source trade: Architect — mapped to Other; reclassify]', 'sourced-import', 'new', false, 'unknown') on conflict (lower(company_name), trade) do nothing;
insert into public.subcontractors (company_name, contact_name, email, phone, website, trade, source_trade, specialties, regions, source_service_area, home_base_city, license_number, notes, source, status, license_verified, availability_status) values ('Progressive Service Company', NULL, NULL, NULL, 'https://callprogressive.com/commercial/plumbing/', 'Plumbing', 'Plumber', 'Residential, Commercial', ARRAY['Triangle (Raleigh–Durham)']::text[], 'Raleigh area', 'Raleigh', NULL, NULL, 'sourced-import', 'new', false, 'unknown') on conflict (lower(company_name), trade) do nothing;
insert into public.subcontractors (company_name, contact_name, email, phone, website, trade, source_trade, specialties, regions, source_service_area, home_base_city, license_number, notes, source, status, license_verified, availability_status) values ('Triangle Mechanical Contractor', NULL, NULL, '919-779-1210', 'https://www.trianglemechanical.com/', 'Plumbing', 'Plumber', 'Commercial, Industrial', ARRAY['Triangle (Raleigh–Durham)']::text[], 'RTP, Raleigh, Durham, Chapel Hill', 'Raleigh', NULL, NULL, 'sourced-import', 'new', false, 'unknown') on conflict (lower(company_name), trade) do nothing;
insert into public.subcontractors (company_name, contact_name, email, phone, website, trade, source_trade, specialties, regions, source_service_area, home_base_city, license_number, notes, source, status, license_verified, availability_status) values ('WyattWorks', NULL, NULL, NULL, 'https://wyattworks.com/charlotte/', 'Plumbing', 'Plumber', 'Residential, Commercial', ARRAY['Charlotte Metro']::text[], 'Charlotte metro', 'Charlotte', NULL, NULL, 'sourced-import', 'new', false, 'unknown') on conflict (lower(company_name), trade) do nothing;
insert into public.subcontractors (company_name, contact_name, email, phone, website, trade, source_trade, specialties, regions, source_service_area, home_base_city, license_number, notes, source, status, license_verified, availability_status) values ('Brothers Air', NULL, NULL, '704-620-6252', 'https://brotherair.com/plumbing/commercial', 'Plumbing', 'Plumber', 'Residential, Commercial', ARRAY['Charlotte Metro']::text[], 'Charlotte area', 'Charlotte', NULL, NULL, 'sourced-import', 'new', false, 'unknown') on conflict (lower(company_name), trade) do nothing;
insert into public.subcontractors (company_name, contact_name, email, phone, website, trade, source_trade, specialties, regions, source_service_area, home_base_city, license_number, notes, source, status, license_verified, availability_status) values ('PMC of NC', NULL, NULL, NULL, 'https://pmcofnc.com/commercial/', 'Plumbing', 'Plumber', 'Commercial tenant upfits', ARRAY['Triangle (Raleigh–Durham)']::text[], 'Durham, Chapel Hill, Raleigh', 'Raleigh', NULL, NULL, 'sourced-import', 'new', false, 'unknown') on conflict (lower(company_name), trade) do nothing;
insert into public.subcontractors (company_name, contact_name, email, phone, website, trade, source_trade, specialties, regions, source_service_area, home_base_city, license_number, notes, source, status, license_verified, availability_status) values ('Fowler & Sons Inc', NULL, NULL, NULL, 'https://www.fowlerandsons.com/commercial-plumbing', 'Plumbing', 'Plumber', 'Commercial', ARRAY['Triangle (Raleigh–Durham)']::text[], 'Raleigh area', 'Raleigh', NULL, NULL, 'sourced-import', 'new', false, 'unknown') on conflict (lower(company_name), trade) do nothing;
insert into public.subcontractors (company_name, contact_name, email, phone, website, trade, source_trade, specialties, regions, source_service_area, home_base_city, license_number, notes, source, status, license_verified, availability_status) values ('All About the Pipes', 'Mary Geiger', NULL, NULL, 'https://www.allaboutthepipes.com/', 'Plumbing', 'Plumber', 'Residential, Commercial', ARRAY['Charlotte Metro']::text[], 'Charlotte area', 'Charlotte', NULL, NULL, 'sourced-import', 'new', false, 'unknown') on conflict (lower(company_name), trade) do nothing;
insert into public.subcontractors (company_name, contact_name, email, phone, website, trade, source_trade, specialties, regions, source_service_area, home_base_city, license_number, notes, source, status, license_verified, availability_status) values ('Queen City Plumbing', 'Justin McFalls', NULL, NULL, 'https://queencityplumbingcharlotte.com/', 'Plumbing', 'Plumber', 'Residential, Commercial', ARRAY['Charlotte Metro']::text[], 'Charlotte area', 'Charlotte', NULL, NULL, 'sourced-import', 'new', false, 'unknown') on conflict (lower(company_name), trade) do nothing;
insert into public.subcontractors (company_name, contact_name, email, phone, website, trade, source_trade, specialties, regions, source_service_area, home_base_city, license_number, notes, source, status, license_verified, availability_status) values ('Guy Roofing', NULL, NULL, NULL, 'https://guyroofing.com/locations/asheville-sc-roofing-company', 'Roofing', 'Roofer', 'Residential, Commercial', ARRAY['Western NC (Asheville)']::text[], 'Asheville, Western NC', 'Asheville', NULL, NULL, 'sourced-import', 'new', false, 'unknown') on conflict (lower(company_name), trade) do nothing;
insert into public.subcontractors (company_name, contact_name, email, phone, website, trade, source_trade, specialties, regions, source_service_area, home_base_city, license_number, notes, source, status, license_verified, availability_status) values ('DLV Roofing', NULL, NULL, NULL, 'https://dlvroofing.com/', 'Roofing', 'Roofer', 'Residential, Commercial', ARRAY['Western NC (Asheville)']::text[], 'Asheville, Charleston area', 'Asheville', NULL, NULL, 'sourced-import', 'new', false, 'unknown') on conflict (lower(company_name), trade) do nothing;
insert into public.subcontractors (company_name, contact_name, email, phone, website, trade, source_trade, specialties, regions, source_service_area, home_base_city, license_number, notes, source, status, license_verified, availability_status) values ('Lane Roofing and Restoration LLC', NULL, NULL, NULL, 'https://laneroofingasheville.com/', 'Roofing', 'Roofer', 'Residential, Commercial', ARRAY['Western NC (Asheville)']::text[], 'Asheville, WNC', 'Asheville', NULL, NULL, 'sourced-import', 'new', false, 'unknown') on conflict (lower(company_name), trade) do nothing;
insert into public.subcontractors (company_name, contact_name, email, phone, website, trade, source_trade, specialties, regions, source_service_area, home_base_city, license_number, notes, source, status, license_verified, availability_status) values ('WNC Roofing', NULL, NULL, NULL, 'https://wncroofing.com/', 'Roofing', 'Roofer', 'Commercial', ARRAY['Western NC (Asheville)']::text[], 'Asheville area', 'Asheville', NULL, NULL, 'sourced-import', 'new', false, 'unknown') on conflict (lower(company_name), trade) do nothing;
insert into public.subcontractors (company_name, contact_name, email, phone, website, trade, source_trade, specialties, regions, source_service_area, home_base_city, license_number, notes, source, status, license_verified, availability_status) values ('Baker Roofing Company', NULL, NULL, NULL, 'https://bakerroofing.com/asheville-roofing-company/', 'Roofing', 'Roofer', 'Commercial', ARRAY['Western NC (Asheville)']::text[], 'Asheville area', 'Asheville', NULL, NULL, 'sourced-import', 'new', false, 'unknown') on conflict (lower(company_name), trade) do nothing;
insert into public.subcontractors (company_name, contact_name, email, phone, website, trade, source_trade, specialties, regions, source_service_area, home_base_city, license_number, notes, source, status, license_verified, availability_status) values ('Asheville Roofing', NULL, NULL, NULL, 'http://ashevilleroofing.com/', 'Roofing', 'Roofer', 'Residential, Commercial', ARRAY['Western NC (Asheville)']::text[], 'Asheville area', 'Asheville', NULL, NULL, 'sourced-import', 'new', false, 'unknown') on conflict (lower(company_name), trade) do nothing;
insert into public.subcontractors (company_name, contact_name, email, phone, website, trade, source_trade, specialties, regions, source_service_area, home_base_city, license_number, notes, source, status, license_verified, availability_status) values ('Kings Roofing Inc', NULL, NULL, NULL, 'https://www.kingsroofingnc.com/', 'Roofing', 'Roofer', 'Residential, Commercial', ARRAY['Western NC (Asheville)']::text[], 'Asheville, WNC', 'Asheville', NULL, NULL, 'sourced-import', 'new', false, 'unknown') on conflict (lower(company_name), trade) do nothing;
insert into public.subcontractors (company_name, contact_name, email, phone, website, trade, source_trade, specialties, regions, source_service_area, home_base_city, license_number, notes, source, status, license_verified, availability_status) values ('Benton Roofing', NULL, NULL, NULL, 'https://bentonroofing.com/', 'Roofing', 'Roofer', 'Commercial', ARRAY['Western NC (Asheville)']::text[], 'Asheville area', 'Asheville', NULL, NULL, 'sourced-import', 'new', false, 'unknown') on conflict (lower(company_name), trade) do nothing;
insert into public.subcontractors (company_name, contact_name, email, phone, website, trade, source_trade, specialties, regions, source_service_area, home_base_city, license_number, notes, source, status, license_verified, availability_status) values ('Jeff''s Roofing Inc', NULL, NULL, NULL, 'https://www.jeffsroofingasheville.com/', 'Roofing', 'Roofer', 'Residential', ARRAY['Western NC (Asheville)']::text[], 'Asheville area', 'Asheville', NULL, NULL, 'sourced-import', 'new', false, 'unknown') on conflict (lower(company_name), trade) do nothing;
insert into public.subcontractors (company_name, contact_name, email, phone, website, trade, source_trade, specialties, regions, source_service_area, home_base_city, license_number, notes, source, status, license_verified, availability_status) values ('Window Source of Eastern NC', NULL, NULL, NULL, 'https://windowsourceeasternnc.com/new-bern-nc/', 'Siding / Exterior', 'Siding & Windows', 'Residential', ARRAY['Eastern NC']::text[], 'New Bern, Eastern NC', 'New Bern', NULL, NULL, 'sourced-import', 'new', false, 'unknown') on conflict (lower(company_name), trade) do nothing;
insert into public.subcontractors (company_name, contact_name, email, phone, website, trade, source_trade, specialties, regions, source_service_area, home_base_city, license_number, notes, source, status, license_verified, availability_status) values ('Anthony''s Windows and Siding', NULL, NULL, NULL, NULL, 'Siding / Exterior', 'Siding & Windows', 'Residential, Commercial', ARRAY['Eastern NC']::text[], 'New Bern area', 'New Bern', NULL, NULL, 'sourced-import', 'new', false, 'unknown') on conflict (lower(company_name), trade) do nothing;
insert into public.subcontractors (company_name, contact_name, email, phone, website, trade, source_trade, specialties, regions, source_service_area, home_base_city, license_number, notes, source, status, license_verified, availability_status) values ('Freedom Roofing Windows & Siding', NULL, NULL, NULL, 'https://freedomrws.com/new-bern-roofing-windows-siding/', 'Siding / Exterior', 'Siding & Windows', 'Residential', ARRAY['Eastern NC']::text[], 'New Bern area', 'New Bern', NULL, NULL, 'sourced-import', 'new', false, 'unknown') on conflict (lower(company_name), trade) do nothing;
insert into public.subcontractors (company_name, contact_name, email, phone, website, trade, source_trade, specialties, regions, source_service_area, home_base_city, license_number, notes, source, status, license_verified, availability_status) values ('New Bern Energy Savers', NULL, NULL, NULL, 'https://newbernenergysavers.com/', 'Siding / Exterior', 'Siding & Windows', 'Residential, Commercial', ARRAY['Eastern NC']::text[], 'New Bern, Pamlico County', 'New Bern', NULL, NULL, 'sourced-import', 'new', false, 'unknown') on conflict (lower(company_name), trade) do nothing;
insert into public.subcontractors (company_name, contact_name, email, phone, website, trade, source_trade, specialties, regions, source_service_area, home_base_city, license_number, notes, source, status, license_verified, availability_status) values ('Hatch Homes', NULL, NULL, NULL, 'https://www.hatchyourhome.com/', 'Siding / Exterior', 'Siding & Windows', 'Residential, Commercial', ARRAY['Charlotte Metro']::text[], 'Charlotte metro', 'Charlotte', NULL, NULL, 'sourced-import', 'new', false, 'unknown') on conflict (lower(company_name), trade) do nothing;
insert into public.subcontractors (company_name, contact_name, email, phone, website, trade, source_trade, specialties, regions, source_service_area, home_base_city, license_number, notes, source, status, license_verified, availability_status) values ('The Remodeling Company LLC', NULL, NULL, NULL, 'https://www.trcofnc.com/new-bern-nc/', 'Siding / Exterior', 'Siding & Windows', 'Residential', ARRAY['Eastern NC']::text[], 'New Bern area', 'New Bern', NULL, NULL, 'sourced-import', 'new', false, 'unknown') on conflict (lower(company_name), trade) do nothing;
insert into public.subcontractors (company_name, contact_name, email, phone, website, trade, source_trade, specialties, regions, source_service_area, home_base_city, license_number, notes, source, status, license_verified, availability_status) values ('Crystal Coast Exteriors', NULL, NULL, NULL, NULL, 'Siding / Exterior', 'Siding & Windows', 'Residential, Commercial', ARRAY['Eastern NC']::text[], 'New Bern area', 'New Bern', NULL, NULL, 'sourced-import', 'new', false, 'unknown') on conflict (lower(company_name), trade) do nothing;
insert into public.subcontractors (company_name, contact_name, email, phone, website, trade, source_trade, specialties, regions, source_service_area, home_base_city, license_number, notes, source, status, license_verified, availability_status) values ('Queen City Cabinet LLC', NULL, NULL, NULL, 'https://www.queencitycabinet.com/', 'Kitchen & Bath / Cabinetry', 'Cabinetry', 'Residential', ARRAY['Charlotte Metro']::text[], 'Charlotte area', 'Charlotte', NULL, NULL, 'sourced-import', 'new', false, 'unknown') on conflict (lower(company_name), trade) do nothing;
insert into public.subcontractors (company_name, contact_name, email, phone, website, trade, source_trade, specialties, regions, source_service_area, home_base_city, license_number, notes, source, status, license_verified, availability_status) values ('Distinctive Cabinets LLC', NULL, NULL, NULL, NULL, 'Kitchen & Bath / Cabinetry', 'Cabinetry', 'Residential custom', ARRAY['Charlotte Metro']::text[], 'Charlotte area', 'Charlotte', NULL, NULL, 'sourced-import', 'new', false, 'unknown') on conflict (lower(company_name), trade) do nothing;
insert into public.subcontractors (company_name, contact_name, email, phone, website, trade, source_trade, specialties, regions, source_service_area, home_base_city, license_number, notes, source, status, license_verified, availability_status) values ('Charlotte Cabinet Installation', NULL, NULL, NULL, 'https://www.charlottecabinetinstallation.com/', 'Kitchen & Bath / Cabinetry', 'Cabinetry', 'Residential, IKEA specialist', ARRAY['Charlotte Metro']::text[], 'Charlotte metro', 'Charlotte', NULL, NULL, 'sourced-import', 'new', false, 'unknown') on conflict (lower(company_name), trade) do nothing;
insert into public.subcontractors (company_name, contact_name, email, phone, website, trade, source_trade, specialties, regions, source_service_area, home_base_city, license_number, notes, source, status, license_verified, availability_status) values ('Cabinet IQ', NULL, NULL, NULL, 'https://cabinetiq.com/charlotte/', 'Kitchen & Bath / Cabinetry', 'Cabinetry', 'Residential custom and stock', ARRAY['Charlotte Metro']::text[], 'Charlotte area', 'Charlotte', NULL, NULL, 'sourced-import', 'new', false, 'unknown') on conflict (lower(company_name), trade) do nothing;
insert into public.subcontractors (company_name, contact_name, email, phone, website, trade, source_trade, specialties, regions, source_service_area, home_base_city, license_number, notes, source, status, license_verified, availability_status) values ('1st Choice Cabinets', NULL, NULL, '704-910-6277', 'https://www.1stchoicecabinets.com/charlotte-area/', 'Kitchen & Bath / Cabinetry', 'Cabinetry', 'Residential, Commercial', ARRAY['Triangle (Raleigh–Durham)', 'Charlotte Metro']::text[], 'Charlotte, Raleigh area', 'Charlotte', NULL, NULL, 'sourced-import', 'new', false, 'unknown') on conflict (lower(company_name), trade) do nothing;
insert into public.subcontractors (company_name, contact_name, email, phone, website, trade, source_trade, specialties, regions, source_service_area, home_base_city, license_number, notes, source, status, license_verified, availability_status) values ('Carolina Cabinet Company', NULL, NULL, NULL, 'https://www.carolinacabinetcompany.com', 'Kitchen & Bath / Cabinetry', 'Cabinetry', 'Residential, Commercial', ARRAY['Triangle (Raleigh–Durham)']::text[], 'Raleigh, Triangle area', 'Raleigh', NULL, NULL, 'sourced-import', 'new', false, 'unknown') on conflict (lower(company_name), trade) do nothing;
insert into public.subcontractors (company_name, contact_name, email, phone, website, trade, source_trade, specialties, regions, source_service_area, home_base_city, license_number, notes, source, status, license_verified, availability_status) values ('Craig''s Cabinets', NULL, NULL, NULL, 'https://www.craigscabinetsraleigh.com/', 'Kitchen & Bath / Cabinetry', 'Cabinetry', 'Residential', ARRAY['Triangle (Raleigh–Durham)']::text[], 'Raleigh, Cary, Wake Forest', 'Raleigh', NULL, NULL, 'sourced-import', 'new', false, 'unknown') on conflict (lower(company_name), trade) do nothing;
insert into public.subcontractors (company_name, contact_name, email, phone, website, trade, source_trade, specialties, regions, source_service_area, home_base_city, license_number, notes, source, status, license_verified, availability_status) values ('Southeastern Tile Connection', NULL, NULL, NULL, 'https://setileconnection.com/', 'Tile / Stone', 'Tile', 'Residential, Commercial', ARRAY['Wilmington / Coastal', 'Triangle (Raleigh–Durham)', 'Western NC (Asheville)']::text[], 'Wilmington, Durham, Asheville', 'Wilmington', NULL, NULL, 'sourced-import', 'new', false, 'unknown') on conflict (lower(company_name), trade) do nothing;
insert into public.subcontractors (company_name, contact_name, email, phone, website, trade, source_trade, specialties, regions, source_service_area, home_base_city, license_number, notes, source, status, license_verified, availability_status) values ('Sousa Tile & Stone', NULL, NULL, NULL, 'https://www.sousatileandstone.com/', 'Tile / Stone', 'Tile', 'Residential, Bathroom remodels', ARRAY['Wilmington / Coastal']::text[], 'Wilmington area', 'Wilmington', NULL, NULL, 'sourced-import', 'new', false, 'unknown') on conflict (lower(company_name), trade) do nothing;
insert into public.subcontractors (company_name, contact_name, email, phone, website, trade, source_trade, specialties, regions, source_service_area, home_base_city, license_number, notes, source, status, license_verified, availability_status) values ('Wilmington Tile and Renovation', NULL, NULL, NULL, 'https://tilewilmington.com/', 'Tile / Stone', 'Tile', 'Residential, Commercial', ARRAY['Wilmington / Coastal']::text[], 'Wilmington area', 'Wilmington', NULL, NULL, 'sourced-import', 'new', false, 'unknown') on conflict (lower(company_name), trade) do nothing;
insert into public.subcontractors (company_name, contact_name, email, phone, website, trade, source_trade, specialties, regions, source_service_area, home_base_city, license_number, notes, source, status, license_verified, availability_status) values ('Wilmington TileCraft', NULL, NULL, NULL, 'https://www.wilmingtontilecraft.com/', 'Tile / Stone', 'Tile', 'Residential, Commercial', ARRAY['Wilmington / Coastal']::text[], 'Wilmington area', 'Wilmington', NULL, NULL, 'sourced-import', 'new', false, 'unknown') on conflict (lower(company_name), trade) do nothing;
insert into public.subcontractors (company_name, contact_name, email, phone, website, trade, source_trade, specialties, regions, source_service_area, home_base_city, license_number, notes, source, status, license_verified, availability_status) values ('Sellers Tile & Custom Counters', NULL, NULL, NULL, 'https://sellers-nc.com/', 'Tile / Stone', 'Tile', 'Residential, Commercial', ARRAY['Wilmington / Coastal']::text[], 'Wilmington area', 'Wilmington', NULL, NULL, 'sourced-import', 'new', false, 'unknown') on conflict (lower(company_name), trade) do nothing;
insert into public.subcontractors (company_name, contact_name, email, phone, website, trade, source_trade, specialties, regions, source_service_area, home_base_city, license_number, notes, source, status, license_verified, availability_status) values ('Seaside Flooring', NULL, NULL, NULL, 'https://www.seasideflooringnc.com/tile-installation', 'Tile / Stone', 'Tile', 'Residential', ARRAY['Wilmington / Coastal']::text[], 'Wilmington, New Hanover, Brunswick, Pender counties', 'Wilmington', NULL, NULL, 'sourced-import', 'new', false, 'unknown') on conflict (lower(company_name), trade) do nothing;
insert into public.subcontractors (company_name, contact_name, email, phone, website, trade, source_trade, specialties, regions, source_service_area, home_base_city, license_number, notes, source, status, license_verified, availability_status) values ('Newcomb and Company', NULL, NULL, NULL, 'https://newcombandcompany.com/', 'Mechanical / HVAC', 'HVAC', 'Residential, Commercial', ARRAY['Wilmington / Coastal', 'Triangle (Raleigh–Durham)']::text[], 'Raleigh, Wilmington', 'Raleigh', NULL, NULL, 'sourced-import', 'new', false, 'unknown') on conflict (lower(company_name), trade) do nothing;
insert into public.subcontractors (company_name, contact_name, email, phone, website, trade, source_trade, specialties, regions, source_service_area, home_base_city, license_number, notes, source, status, license_verified, availability_status) values ('Carolina Commercial Systems', NULL, NULL, NULL, 'https://carolinacommercialsystems.com/', 'Mechanical / HVAC', 'HVAC', 'Residential, Commercial', ARRAY['Triangle (Raleigh–Durham)']::text[], 'Raleigh area', 'Raleigh', NULL, NULL, 'sourced-import', 'new', false, 'unknown') on conflict (lower(company_name), trade) do nothing;
insert into public.subcontractors (company_name, contact_name, email, phone, website, trade, source_trade, specialties, regions, source_service_area, home_base_city, license_number, notes, source, status, license_verified, availability_status) values ('Allen Kelly & Co', NULL, NULL, NULL, 'https://allenkelly.com/', 'Mechanical / HVAC', 'HVAC', 'Residential, Commercial', ARRAY['Triangle (Raleigh–Durham)']::text[], 'Raleigh area', 'Raleigh', NULL, NULL, 'sourced-import', 'new', false, 'unknown') on conflict (lower(company_name), trade) do nothing;
insert into public.subcontractors (company_name, contact_name, email, phone, website, trade, source_trade, specialties, regions, source_service_area, home_base_city, license_number, notes, source, status, license_verified, availability_status) values ('Air Experts', NULL, NULL, NULL, 'https://yourairexperts.com/', 'Mechanical / HVAC', 'HVAC', 'Residential', ARRAY['Triangle (Raleigh–Durham)']::text[], 'Triangle region', 'Raleigh', NULL, NULL, 'sourced-import', 'new', false, 'unknown') on conflict (lower(company_name), trade) do nothing;
insert into public.subcontractors (company_name, contact_name, email, phone, website, trade, source_trade, specialties, regions, source_service_area, home_base_city, license_number, notes, source, status, license_verified, availability_status) values ('Carolina Comfort Air', NULL, NULL, NULL, 'https://www.carolinacomfortair.com/', 'Mechanical / HVAC', 'HVAC', 'Residential, Commercial', ARRAY['Triangle (Raleigh–Durham)']::text[], 'Raleigh area', 'Raleigh', NULL, NULL, 'sourced-import', 'new', false, 'unknown') on conflict (lower(company_name), trade) do nothing;
insert into public.subcontractors (company_name, contact_name, email, phone, website, trade, source_trade, specialties, regions, source_service_area, home_base_city, license_number, notes, source, status, license_verified, availability_status) values ('Raleigh Heating & Air', NULL, NULL, NULL, 'https://raleighheatingandair.com/', 'Mechanical / HVAC', 'HVAC', 'Residential, Commercial', ARRAY['Triangle (Raleigh–Durham)']::text[], 'Raleigh area', 'Raleigh', NULL, NULL, 'sourced-import', 'new', false, 'unknown') on conflict (lower(company_name), trade) do nothing;
insert into public.subcontractors (company_name, contact_name, email, phone, website, trade, source_trade, specialties, regions, source_service_area, home_base_city, license_number, notes, source, status, license_verified, availability_status) values ('Call Dad AC & Heating', NULL, NULL, NULL, 'https://www.calldad.com/', 'Mechanical / HVAC', 'HVAC', 'Residential, Commercial', ARRAY['Triangle (Raleigh–Durham)']::text[], 'Raleigh area', 'Raleigh', NULL, NULL, 'sourced-import', 'new', false, 'unknown') on conflict (lower(company_name), trade) do nothing;
insert into public.subcontractors (company_name, contact_name, email, phone, website, trade, source_trade, specialties, regions, source_service_area, home_base_city, license_number, notes, source, status, license_verified, availability_status) values ('Blaze Heating Cooling Electrical Plumbing', NULL, NULL, NULL, 'https://blazeair.com/', 'Mechanical / HVAC', 'HVAC', 'Residential, Commercial', ARRAY['Charlotte Metro', 'Triangle (Raleigh–Durham)', 'Triad (Greensboro–Winston-Salem)', 'Fayetteville / Sandhills', 'Wilmington / Coastal', 'Eastern NC', 'Western NC (Asheville)']::text[], 'North Carolina wide', 'Regional', NULL, NULL, 'sourced-import', 'new', false, 'unknown') on conflict (lower(company_name), trade) do nothing;
insert into public.subcontractors (company_name, contact_name, email, phone, website, trade, source_trade, specialties, regions, source_service_area, home_base_city, license_number, notes, source, status, license_verified, availability_status) values ('Comfort Monster', NULL, NULL, NULL, 'https://comfortmonster.com/', 'Mechanical / HVAC', 'HVAC', 'Residential, Commercial', ARRAY['Triangle (Raleigh–Durham)']::text[], 'Raleigh area', 'Raleigh', NULL, NULL, 'sourced-import', 'new', false, 'unknown') on conflict (lower(company_name), trade) do nothing;
insert into public.subcontractors (company_name, contact_name, email, phone, website, trade, source_trade, specialties, regions, source_service_area, home_base_city, license_number, notes, source, status, license_verified, availability_status) values ('Quality Comfort Services Inc', NULL, NULL, NULL, 'https://qcshvac.com/', 'Mechanical / HVAC', 'HVAC', 'Commercial', ARRAY['Triangle (Raleigh–Durham)']::text[], 'Raleigh area', 'Raleigh', NULL, NULL, 'sourced-import', 'new', false, 'unknown') on conflict (lower(company_name), trade) do nothing;
insert into public.subcontractors (company_name, contact_name, email, phone, website, trade, source_trade, specialties, regions, source_service_area, home_base_city, license_number, notes, source, status, license_verified, availability_status) values ('Jackson & Sons', NULL, NULL, NULL, 'https://www.jacksonandsons.com/', 'Mechanical / HVAC', 'HVAC', 'Residential, Commercial', ARRAY['Eastern NC']::text[], 'New Bern, Greenville area', 'New Bern', NULL, NULL, 'sourced-import', 'new', false, 'unknown') on conflict (lower(company_name), trade) do nothing;
insert into public.subcontractors (company_name, contact_name, email, phone, website, trade, source_trade, specialties, regions, source_service_area, home_base_city, license_number, notes, source, status, license_verified, availability_status) values ('BJ Plumbing', NULL, NULL, '252-512-5651', 'https://www.bjplumbing.com/', 'Mechanical / HVAC', 'HVAC', 'Residential, Commercial', ARRAY['Eastern NC']::text[], 'Greenville area', 'Greenville', NULL, NULL, 'sourced-import', 'new', false, 'unknown') on conflict (lower(company_name), trade) do nothing;
insert into public.subcontractors (company_name, contact_name, email, phone, website, trade, source_trade, specialties, regions, source_service_area, home_base_city, license_number, notes, source, status, license_verified, availability_status) values ('NuBlue Service Group', NULL, NULL, NULL, 'https://callnublue.com/', 'Mechanical / HVAC', 'HVAC', 'Residential, Commercial', ARRAY['Eastern NC']::text[], 'Greenville area', 'Greenville', NULL, NULL, 'sourced-import', 'new', false, 'unknown') on conflict (lower(company_name), trade) do nothing;
insert into public.subcontractors (company_name, contact_name, email, phone, website, trade, source_trade, specialties, regions, source_service_area, home_base_city, license_number, notes, source, status, license_verified, availability_status) values ('Norris Mechanical', NULL, NULL, NULL, 'https://norrismechanical.com/', 'Mechanical / HVAC', 'HVAC', 'Residential, Commercial', ARRAY['Eastern NC']::text[], 'Elizabeth City, Northeastern NC', 'Elizabeth City', NULL, NULL, 'sourced-import', 'new', false, 'unknown') on conflict (lower(company_name), trade) do nothing;
insert into public.subcontractors (company_name, contact_name, email, phone, website, trade, source_trade, specialties, regions, source_service_area, home_base_city, license_number, notes, source, status, license_verified, availability_status) values ('Raleigh Electric Company', NULL, NULL, NULL, 'https://raleighelectriccompany.com/', 'Electrical', 'Electrician', 'Residential, Small commercial', ARRAY['Triangle (Raleigh–Durham)']::text[], 'Raleigh area', 'Raleigh', NULL, NULL, 'sourced-import', 'new', false, 'unknown') on conflict (lower(company_name), trade) do nothing;
insert into public.subcontractors (company_name, contact_name, email, phone, website, trade, source_trade, specialties, regions, source_service_area, home_base_city, license_number, notes, source, status, license_verified, availability_status) values ('Wheeler Electrical Company', NULL, NULL, NULL, 'https://www.wheelerelectricalinc.com/', 'Electrical', 'Electrician', 'Residential, Commercial', ARRAY['Triangle (Raleigh–Durham)']::text[], 'Raleigh area', 'Raleigh', NULL, NULL, 'sourced-import', 'new', false, 'unknown') on conflict (lower(company_name), trade) do nothing;
insert into public.subcontractors (company_name, contact_name, email, phone, website, trade, source_trade, specialties, regions, source_service_area, home_base_city, license_number, notes, source, status, license_verified, availability_status) values ('NC Express Services LLC', NULL, NULL, NULL, 'https://www.ncexpress.pro', 'Electrical', 'Electrician', 'Residential, Commercial', ARRAY['Triangle (Raleigh–Durham)']::text[], 'Raleigh area', 'Raleigh', NULL, NULL, 'sourced-import', 'new', false, 'unknown') on conflict (lower(company_name), trade) do nothing;
insert into public.subcontractors (company_name, contact_name, email, phone, website, trade, source_trade, specialties, regions, source_service_area, home_base_city, license_number, notes, source, status, license_verified, availability_status) values ('ARC Electric', NULL, NULL, NULL, 'https://arcelectric.com/', 'Electrical', 'Electrician', 'Residential, Commercial', ARRAY['Triangle (Raleigh–Durham)']::text[], 'Raleigh area', 'Raleigh', NULL, NULL, 'sourced-import', 'new', false, 'unknown') on conflict (lower(company_name), trade) do nothing;
insert into public.subcontractors (company_name, contact_name, email, phone, website, trade, source_trade, specialties, regions, source_service_area, home_base_city, license_number, notes, source, status, license_verified, availability_status) values ('Mabry''s Electrical Service', NULL, NULL, NULL, 'https://mabryelectrical.com/', 'Electrical', 'Electrician', 'Residential, Commercial', ARRAY['Wilmington / Coastal', 'Triangle (Raleigh–Durham)']::text[], 'Raleigh, Wilmington', 'Raleigh', NULL, NULL, 'sourced-import', 'new', false, 'unknown') on conflict (lower(company_name), trade) do nothing;
insert into public.subcontractors (company_name, contact_name, email, phone, website, trade, source_trade, specialties, regions, source_service_area, home_base_city, license_number, notes, source, status, license_verified, availability_status) values ('Mr. Electric of West Raleigh', NULL, NULL, NULL, 'https://mrelectric.com/west-raleigh', 'Electrical', 'Electrician', 'Residential, Commercial', ARRAY['Triangle (Raleigh–Durham)']::text[], 'Raleigh area', 'Raleigh', NULL, NULL, 'sourced-import', 'new', false, 'unknown') on conflict (lower(company_name), trade) do nothing;
insert into public.subcontractors (company_name, contact_name, email, phone, website, trade, source_trade, specialties, regions, source_service_area, home_base_city, license_number, notes, source, status, license_verified, availability_status) values ('Point Electric LLC', NULL, NULL, NULL, 'https://pointelectricnc.com/', 'Electrical', 'Electrician', 'Residential, Commercial', ARRAY['Triangle (Raleigh–Durham)']::text[], 'Raleigh area', 'Raleigh', NULL, NULL, 'sourced-import', 'new', false, 'unknown') on conflict (lower(company_name), trade) do nothing;
insert into public.subcontractors (company_name, contact_name, email, phone, website, trade, source_trade, specialties, regions, source_service_area, home_base_city, license_number, notes, source, status, license_verified, availability_status) values ('Right Electrical Services', NULL, NULL, NULL, 'https://raleighelectricians.com/', 'Electrical', 'Electrician', 'Residential, Commercial', ARRAY['Triangle (Raleigh–Durham)']::text[], 'Raleigh, Wake County', 'Raleigh', NULL, NULL, 'sourced-import', 'new', false, 'unknown') on conflict (lower(company_name), trade) do nothing;
insert into public.subcontractors (company_name, contact_name, email, phone, website, trade, source_trade, specialties, regions, source_service_area, home_base_city, license_number, notes, source, status, license_verified, availability_status) values ('D C Electric of Raleigh', NULL, NULL, NULL, 'https://dcelectricofraleigh.com/', 'Electrical', 'Electrician', 'Residential, Commercial', ARRAY['Triangle (Raleigh–Durham)']::text[], 'Raleigh area', 'Raleigh', NULL, NULL, 'sourced-import', 'new', false, 'unknown') on conflict (lower(company_name), trade) do nothing;
insert into public.subcontractors (company_name, contact_name, email, phone, website, trade, source_trade, specialties, regions, source_service_area, home_base_city, license_number, notes, source, status, license_verified, availability_status) values ('Bolton Service', NULL, NULL, NULL, 'https://boltonservice.com/', 'Electrical', 'Electrician', 'Commercial', ARRAY['Triangle (Raleigh–Durham)']::text[], 'Raleigh area', 'Raleigh', NULL, NULL, 'sourced-import', 'new', false, 'unknown') on conflict (lower(company_name), trade) do nothing;
insert into public.subcontractors (company_name, contact_name, email, phone, website, trade, source_trade, specialties, regions, source_service_area, home_base_city, license_number, notes, source, status, license_verified, availability_status) values ('River Dog Plumbing', NULL, NULL, NULL, NULL, 'Plumbing', 'Plumber', 'Residential, Commercial', ARRAY['Eastern NC']::text[], 'New Bern area', 'New Bern', NULL, NULL, 'sourced-import', 'new', false, 'unknown') on conflict (lower(company_name), trade) do nothing;
insert into public.subcontractors (company_name, contact_name, email, phone, website, trade, source_trade, specialties, regions, source_service_area, home_base_city, license_number, notes, source, status, license_verified, availability_status) values ('Pipe Works Plumbing', NULL, NULL, NULL, NULL, 'Plumbing', 'Plumber', 'Residential, Commercial', ARRAY['Eastern NC']::text[], 'New Bern area', 'New Bern', NULL, NULL, 'sourced-import', 'new', false, 'unknown') on conflict (lower(company_name), trade) do nothing;
insert into public.subcontractors (company_name, contact_name, email, phone, website, trade, source_trade, specialties, regions, source_service_area, home_base_city, license_number, notes, source, status, license_verified, availability_status) values ('Nobles Plumbing & Drain Cleaning', NULL, NULL, NULL, NULL, 'Plumbing', 'Plumber', 'Residential, Commercial', ARRAY['Eastern NC']::text[], 'New Bern area', 'New Bern', NULL, NULL, 'sourced-import', 'new', false, 'unknown') on conflict (lower(company_name), trade) do nothing;
insert into public.subcontractors (company_name, contact_name, email, phone, website, trade, source_trade, specialties, regions, source_service_area, home_base_city, license_number, notes, source, status, license_verified, availability_status) values ('Signature Exteriors', NULL, NULL, NULL, 'https://signatureexteriorsinc.com/', 'Roofing', 'Roofer', 'Residential, Commercial', ARRAY['Charlotte Metro']::text[], 'Charlotte, Greenville SC', 'Charlotte', NULL, NULL, 'sourced-import', 'new', false, 'unknown') on conflict (lower(company_name), trade) do nothing;
insert into public.subcontractors (company_name, contact_name, email, phone, website, trade, source_trade, specialties, regions, source_service_area, home_base_city, license_number, notes, source, status, license_verified, availability_status) values ('A&M Premier Roofing & Construction', NULL, NULL, NULL, 'https://amprco.com/', 'Roofing', 'Roofer', 'Residential, Commercial', ARRAY['Triangle (Raleigh–Durham)', 'Charlotte Metro', 'Triad (Greensboro–Winston-Salem)', 'Western NC (Asheville)']::text[], 'Raleigh, Greensboro, Charlotte, Asheville', 'Regional', NULL, NULL, 'sourced-import', 'new', false, 'unknown') on conflict (lower(company_name), trade) do nothing;
insert into public.subcontractors (company_name, contact_name, email, phone, website, trade, source_trade, specialties, regions, source_service_area, home_base_city, license_number, notes, source, status, license_verified, availability_status) values ('Iron Horse Roofing', NULL, NULL, '984-205-5638', 'https://ironhorseroofing.com/', 'Roofing', 'Roofer', 'Residential', ARRAY['Triangle (Raleigh–Durham)', 'Charlotte Metro']::text[], 'Raleigh, Charlotte, Greenville SC', 'Regional', NULL, NULL, 'sourced-import', 'new', false, 'unknown') on conflict (lower(company_name), trade) do nothing;
insert into public.subcontractors (company_name, contact_name, email, phone, website, trade, source_trade, specialties, regions, source_service_area, home_base_city, license_number, notes, source, status, license_verified, availability_status) values ('Roof Medic', NULL, NULL, NULL, 'https://roofmedic.com/', 'Roofing', 'Roofer', 'Residential, Commercial', ARRAY['Triangle (Raleigh–Durham)', 'Charlotte Metro']::text[], 'Charlotte, Raleigh', 'Charlotte', NULL, NULL, 'sourced-import', 'new', false, 'unknown') on conflict (lower(company_name), trade) do nothing;
insert into public.subcontractors (company_name, contact_name, email, phone, website, trade, source_trade, specialties, regions, source_service_area, home_base_city, license_number, notes, source, status, license_verified, availability_status) values ('The Remodeling Company LLC', NULL, NULL, NULL, 'https://www.trcofnc.com/', 'Roofing', 'Roofer', 'Residential', ARRAY['Triangle (Raleigh–Durham)', 'Eastern NC']::text[], 'Raleigh, New Bern, Greenville', 'Raleigh', NULL, NULL, 'sourced-import', 'new', false, 'unknown') on conflict (lower(company_name), trade) do nothing;
insert into public.subcontractors (company_name, contact_name, email, phone, website, trade, source_trade, specialties, regions, source_service_area, home_base_city, license_number, notes, source, status, license_verified, availability_status) values ('Camden Roofing', NULL, NULL, NULL, 'https://camdenroofinggc.com', 'Roofing', 'Roofer', 'Residential', ARRAY['Charlotte Metro', 'Triangle (Raleigh–Durham)', 'Triad (Greensboro–Winston-Salem)', 'Fayetteville / Sandhills', 'Wilmington / Coastal', 'Eastern NC', 'Western NC (Asheville)']::text[], 'North Carolina wide', 'Regional', NULL, NULL, 'sourced-import', 'new', false, 'unknown') on conflict (lower(company_name), trade) do nothing;
insert into public.subcontractors (company_name, contact_name, email, phone, website, trade, source_trade, specialties, regions, source_service_area, home_base_city, license_number, notes, source, status, license_verified, availability_status) values ('TeamCraft Roofing', NULL, NULL, NULL, 'https://www.tcrfg.com/charlotte', 'Roofing', 'Roofer', 'Commercial, Industrial', ARRAY['Charlotte Metro']::text[], 'Charlotte area', 'Charlotte', NULL, NULL, 'sourced-import', 'new', false, 'unknown') on conflict (lower(company_name), trade) do nothing;
insert into public.subcontractors (company_name, contact_name, email, phone, website, trade, source_trade, specialties, regions, source_service_area, home_base_city, license_number, notes, source, status, license_verified, availability_status) values ('CentiMark', NULL, NULL, NULL, 'https://www.centimark.com/locations/raleigh-north-carolina', 'Roofing', 'Roofer', 'Commercial', ARRAY['Charlotte Metro', 'Triangle (Raleigh–Durham)', 'Triad (Greensboro–Winston-Salem)', 'Fayetteville / Sandhills', 'Wilmington / Coastal', 'Eastern NC', 'Western NC (Asheville)']::text[], 'Raleigh, Wilmington, Greenville, statewide', 'Raleigh', NULL, NULL, 'sourced-import', 'new', false, 'unknown') on conflict (lower(company_name), trade) do nothing;
insert into public.subcontractors (company_name, contact_name, email, phone, website, trade, source_trade, specialties, regions, source_service_area, home_base_city, license_number, notes, source, status, license_verified, availability_status) values ('Garcias Painting', 'Garcia', NULL, '980-333-5760', NULL, 'Drywall / Painting', 'Painter', 'Painting', ARRAY['Charlotte Metro']::text[], 'Charlotte area', 'Charlotte', NULL, 'Slogan: Serving God Through Serving Others. White Ford Transit van, NC plate VFZ-5429. QR code on rear window. Spotted on Charlottetown Ave. Source: photo from Darius 2026-04-16.', 'sourced-import', 'new', false, 'unknown') on conflict (lower(company_name), trade) do nothing;
insert into public.subcontractors (company_name, contact_name, email, phone, website, trade, source_trade, specialties, regions, source_service_area, home_base_city, license_number, notes, source, status, license_verified, availability_status) values ('William Tyler', 'William Tyler', NULL, '(252) 202-8420', NULL, 'Other', 'TBD', NULL, ARRAY['Eastern NC']::text[], 'Coinjock / Currituck County NC', 'Coinjock, NC', NULL, 'Referred by Deon Walton 2026-07-29 via Telegram forward. Recommended to Allona for 107 Cherokee Trail (Iantha) project. Trade/specialty not yet specified — needs qualification call. Home number listed as Coinjock, NC. [source trade: TBD — mapped to Other; reclassify]', 'sourced-import', 'new', false, 'unknown') on conflict (lower(company_name), trade) do nothing;

-- 119 rows; 2 with no region match (flagged in notes).
