import { ServiceCalculatorConfig } from '@/components/ServiceCalculator';

export type ServicePurchaseType = 'fixed' | 'priced' | 'review' | 'recurring';
export type ServicePrimaryAction =
  | 'buy'
  | 'pricing'
  | 'review'
  | 'plan';

export type ServiceCardData = {
  slug: string;
  title: string;
  summary: string;
  pain: string;
  outcome: string;
  details: string[];
  included?: string[];
  notIncluded?: string[];
  fit: string;
  purchaseType: ServicePurchaseType;
  primaryAction: ServicePrimaryAction;
  cta: string;
  detailHref: string;
  ctaHref?: string;
  itemKey?: string;
  calculator?: ServiceCalculatorConfig;
  monthlyPrice?: string;
  monthlyLimit?: string;
  turnaround?: string;
  tag?: string;
  proofTitle?: string;
  proofBody?: string;
  pricingNote?: string;
  inputsNeeded?: string[];
  pricingLogic?: string[];
  nextStep?: string;
  why?: string;
  warnings?: string[];
};

export type AvatarPageData = {
  slug: string;
  eyebrow: string;
  shortLabel: string;
  heroTitle: string;
  heroSubtitle: string;
  painPoints: string[];
  outcomes: string[];
  fixed?: ServiceCardData[];
  priced?: ServiceCardData[];
  review?: ServiceCardData[];
  recurring?: ServiceCardData[];
  recurringIntro?: string;
  stageGroups?: {
    title: string;
    intro: string;
    serviceSlugs: string[];
  }[];
};

function detailHref(avatar: string, service: string) {
  return `/services/${avatar}/${service}`;
}

const homeownerServices: AvatarPageData = {
  slug: 'homeowners',
  eyebrow: 'Homeowners',
  shortLabel: 'For Homeowners',
  heroTitle: 'Residential project help before the work gets expensive and after the job starts feeling loose',
  heroSubtitle:
    'Southern Cities helps homeowners get clearer next steps, more realistic budget direction, cleaner permit paths, and steadier project follow-through before small issues turn into expensive ones.',
  painPoints: [
    'You need a better read before spending more money.',
    'Permit questions and paperwork are creating hesitation.',
    'Budget uncertainty is making decisions harder.',
    'The job needs stronger follow-through than it has now.',
  ],
  outcomes: [
    'A clearer next step before commitment.',
    'Better budget direction before the wrong spend happens.',
    'Cleaner permit handling and less confusion.',
    'Stronger support once the work is underway.',
  ],
  fixed: [
    {
      slug: 'home-assessment',
      title: 'Home Assessment',
      summary: 'A paid property review for homeowners who need a clearer next step before committing to more work or more money.',
      pain: 'You do not want to keep guessing what to fix, what to defer, or what matters most first.',
      outcome: 'Get a focused review and a practical recommendation you can act on.',
      details: ['Property walkthrough', 'Condition notes', 'Priority repair list', 'Clear recommendation on what to do next'],
      included: ['One property review', 'Written priority notes', 'Clear next-step recommendation'],
      notIncluded: ['Full construction management', 'Permit filing', 'Detailed contractor bid package'],
      fit: 'Best when you need a grounded next step before the project gets more expensive.',
      purchaseType: 'fixed',
      primaryAction: 'buy',
      cta: 'Buy Now',
      detailHref: detailHref('homeowners', 'home-assessment'),
      itemKey: 'home-assessment',
      monthlyPrice: '$299 assessment',
      turnaround: 'Typical turnaround: 2 business days',
      proofTitle: 'Useful before more money goes out the door',
      proofBody: 'This works best when the homeowner needs a stronger read before approving more work or budget.',
      why: 'Contained scope, clear deliverable, honest fixed-price starter offer.',
    },
    {
      slug: 'owner-consultation',
      title: 'Owner Consultation',
      summary: 'A direct consultation for homeowners who need a clear answer on scope, permits, budget, or project decisions.',
      pain: 'You need a practical answer before making the wrong call on the project.',
      outcome: 'Get direct guidance, risk callouts, and a stronger decision path.',
      details: ['Project review', 'Practical guidance', 'Risk callouts', 'Recommended next step'],
      included: ['Focused consultation', 'Decision guidance', 'Next-step summary'],
      notIncluded: ['Permit submission', 'Ongoing oversight', 'Detailed budget package'],
      fit: 'Best when the issue is not just the work itself, but the decisions around it.',
      purchaseType: 'fixed',
      primaryAction: 'buy',
      cta: 'Buy Now',
      detailHref: detailHref('homeowners', 'owner-consultation'),
      itemKey: 'owner-consultation',
      monthlyPrice: '$349',
      turnaround: 'Scheduled consultation',
      proofTitle: 'Useful when the decision is what is holding you up',
      proofBody: 'This gives homeowners a cleaner read before they commit to a contractor, permit path, or budget decision.',
      why: 'Defined advisory scope, clean fixed-price purchase.',
    },
    {
      slug: 'permit-path-review',
      title: 'Permit Path Review',
      summary: 'A paid early review for homeowners who need to understand permit requirements before work starts creating waste and confusion.',
      pain: 'You do not want the permit path to become an expensive surprise after planning is already underway.',
      outcome: 'Get a clearer read on what permitting likely requires and what to do next.',
      details: ['Permit requirements review', 'Likely approval path', 'Known risk points', 'Recommended next step'],
      included: ['Early permit-path review', 'Risk notes', 'Next-step guidance'],
      notIncluded: ['Permit submission', 'GC-of-record role', 'Ongoing permit management'],
      fit: 'Best when you need permit clarity before moving further.',
      purchaseType: 'fixed',
      primaryAction: 'buy',
      cta: 'Buy Now',
      detailHref: detailHref('homeowners', 'permit-path-review'),
      itemKey: 'permit-path-review',
      monthlyPrice: '$299 assessment',
      turnaround: 'Typical turnaround: 2 business days',
      proofTitle: 'Useful before the permit side gets messy',
      proofBody: 'This is an early-stage clarity offer, not a full permit-administration package.',
      why: 'Small, clearly bounded deliverable that can be sold cleanly.',
    },
  ],
  priced: [
    {
      slug: 'home-project-budget-review',
      title: 'Home Project Budget Review',
      summary: 'A pricing-direction service for homeowners who need a more realistic budget range before deciding how to move.',
      pain: 'You need a better number before approving scope, timeline, or the next spend.',
      outcome: 'Get pricing direction based on the project inputs that matter most.',
      details: ['Project type review', 'Budget range from project inputs', 'Visible-condition assumptions', 'Summary of likely cost range'],
      included: ['Budget-direction review', 'Range-based pricing guidance', 'Assumption notes'],
      notIncluded: ['Fixed contractor bid', 'Detailed plan takeoff', 'Guaranteed construction price'],
      fit: 'Best when you need pricing direction before the project gets more expensive or more confusing.',
      purchaseType: 'priced',
      primaryAction: 'pricing',
      cta: 'Get Pricing',
      detailHref: detailHref('homeowners', 'home-project-budget-review'),
      ctaHref: '/pricing/home-project-budget-review',
      pricingNote: 'Price is shaped by project type, scale, and visible condition.',
      proofTitle: 'Useful before a rough guess becomes the budget',
      proofBody: 'This is for cleaner direction, not a fake instant bid.',
      why: 'Inputs matter, so it needs pricing logic instead of cart behavior.',
    },
  ],
  review: [
    {
      slug: 'permit-administration',
      title: 'Permit Administration',
      summary: 'Permit help for homeowners who need filings, corrections, and inspection coordination handled more tightly.',
      pain: 'The permit side is creating too much confusion, delay, or repeated follow-up.',
      outcome: 'Start with a review so permit handling can be scoped responsibly.',
      details: ['Permit review', 'Submission coordination', 'Correction handling', 'Inspection scheduling support'],
      included: ['Review of current permit needs', 'Permit support scope recommendation', 'Next-step plan'],
      notIncluded: ['Automatic fixed-price permit service', 'Unlimited corrections', 'Full construction oversight by default'],
      fit: 'Best when the permit side is becoming the bottleneck.',
      purchaseType: 'review',
      primaryAction: 'review',
      cta: 'Request Permit Review',
      detailHref: detailHref('homeowners', 'permit-administration'),
      ctaHref: '/review/permit-administration',
      proofTitle: 'Useful when real file conditions matter',
      proofBody: 'Permit work is different in every jurisdiction, so we scope it to your file before we price it.',
      why: 'Variable scope, jurisdiction complexity, and file condition make cart behavior dishonest.',
    },
    {
      slug: 'construction-oversight',
      title: 'Construction Oversight',
      summary: 'Help for active residential jobs that need tighter coordination, clearer milestones, and steadier follow-through.',
      pain: 'The work is active, but the job still needs stronger control than it has now.',
      outcome: 'Start with a review so the oversight scope matches the project risk and job condition.',
      details: ['Project review', 'Oversight scope', 'Milestone structure', 'Coordination support plan'],
      included: ['Initial project review', 'Oversight recommendation', 'Next-step scope discussion'],
      notIncluded: ['Flat-fee universal oversight package', 'Unlimited site visits', 'Automatic GC role'],
      fit: 'Best when the work is moving, but nobody is managing it closely enough.',
      purchaseType: 'review',
      primaryAction: 'review',
      cta: 'Request Oversight Review',
      detailHref: detailHref('homeowners', 'construction-oversight'),
      ctaHref: '/review/construction-oversight',
      proofTitle: 'Useful when the project needs real control',
      proofBody: 'Oversight should be scoped based on the actual file, not sold as a one-size-fits-all cart item.',
      why: 'Active-job complexity is too variable for ecommerce treatment.',
    },
  ],
};

const investorServices: AvatarPageData = {
  slug: 'investors',
  eyebrow: 'Investors',
  shortLabel: 'For Investors',
  heroTitle: 'Construction made easier for investors who need the right support piece at the right stage',
  heroSubtitle:
    'Southern Cities helps investors buy the specific support they need before buying, before startup, during draw and lender pressure, and during active execution without stepping into one giant undefined construction relationship.',
  painPoints: [
    'The numbers still are not solid enough yet.',
    'Contractor setup decisions still feel loose.',
    'Lender, draw, and bid support need more discipline.',
    'Active work is eating time, margin, or momentum.',
  ],
  outcomes: [
    'A better read before money goes out.',
    'Cleaner startup decisions and better contractor fit.',
    'Stronger lender and draw support.',
    'Better control once the job is active.',
  ],
  stageGroups: [
    {
      title: 'Before you buy',
      intro: 'Use these when you need a cleaner read before approving a deal, a rehab number, or a contractor decision.',
      serviceSlugs: ['investor-review', 'budget-review', 'contractor-grade-budget', 'permit-local-compliance-review', 'contractor-fit-consultation'],
    },
    {
      title: 'Before you start',
      intro: 'Use these when the project is real, but startup decisions still need to be tightened before work or money moves too far.',
      serviceSlugs: ['regional-investor-setup-consultation', 'contractor-scope-mapping', 'bid-coordination-contractor-match', 'scope-timeline-setup', 'materials-logistics-setup'],
    },
    {
      title: 'During lender and draw setup',
      intro: 'Use these when weak scope support, weak bid backup, or weak draw support starts slowing funding conversations down.',
      serviceSlugs: ['draw-review-support', 'draw-strategy-alignment', 'cashflow-planning', 'lender-scope-bid-package'],
    },
    {
      title: 'During active execution',
      intro: 'Use these when the job is already moving and tighter follow-through matters more than broad advice.',
      serviceSlugs: ['construction-oversight', 'owner-controlled-build', 'project-coordination-control', 'full-construction-management'],
    },
    {
      title: 'Ongoing support',
      intro: 'Use these when the same investor-side project questions keep repeating across active files.',
      serviceSlugs: ['turn-support-plan', 'operator-support-plan', 'project-support-retainer', 'due-diligence-package', 'construction-planning-package'],
    },
  ],
  fixed: [
    {
      slug: 'investor-review',
      title: 'Investor Deal & Scope Review',
      summary: 'A pre-acquisition underwriting opinion. You send the deal; we send back scope feasibility, a rough budget range with confidence levels, the construction risks, and the walk-away trigger.',
      pain: 'You need a construction-side opinion on this deal before earnest money goes hard — but you do not need a line-item budget yet.',
      outcome: 'Get a decision-grade read: scope feasibility, a rough budget range you can underwrite with, the risks worth knowing before close, and a clear go / renegotiate / walk recommendation.',
      details: ['Scope feasibility read', 'Rough budget range with confidence levels', 'Construction risk callouts', 'Realistic timeline range', 'Walk-away trigger'],
      included: ['Decision-grade scope and budget range', 'Construction risk callouts', 'Timeline range', 'Walk-away threshold'],
      notIncluded: ['Line-item budget audit — see Budget & Scope Review', 'Site walk', 'Contractor bid collection', 'Appraisal or BPO'],
      fit: 'Best before earnest money goes hard on a deal you do not own yet — when you need a number you can underwrite with, not a bid sheet.',
      purchaseType: 'fixed',
      primaryAction: 'buy',
      cta: 'Buy Now',
      detailHref: detailHref('investors', 'investor-review'),
      itemKey: 'investor-review',
      monthlyPrice: '$499',
      turnaround: 'Typical turnaround: 2 business days',
      proofTitle: 'Useful before you commit to the wrong deal',
      proofBody: 'A rough range is enough to underwrite a buy decision. Line-item precision comes after you close — that is a different product.',
      why: 'Investors need a number they can plug into deal math, not a contractor bid sheet.',
    },
    {
      slug: 'permit-local-compliance-review',
      title: 'Permit & Local Compliance Review',
      summary: 'A paid early review for investors who need a cleaner local permit and compliance read before the deal closes.',
      pain: 'You do not want the rehab path, permit risk, or local compliance issues to become an expensive surprise after closing.',
      outcome: 'Get a focused review of likely permit path, compliance risk, and the next decision before you commit.',
      details: ['Permit-path review', 'Local compliance notes', 'Risk callouts', 'Recommended next step'],
      included: ['Project review', 'Permit and compliance notes', 'Decision guidance'],
      notIncluded: ['Permit submission', 'Jurisdiction filing', 'Ongoing permit administration'],
      fit: 'Best when local permit or compliance risk could change the deal decision.',
      purchaseType: 'fixed',
      primaryAction: 'buy',
      cta: 'Buy Now',
      detailHref: detailHref('investors', 'permit-local-compliance-review'),
      itemKey: 'permit-local-compliance-review',
      monthlyPrice: '$399',
      turnaround: 'Typical turnaround: 2 business days',
      proofTitle: 'Useful before local issues wreck the deal math',
      proofBody: 'This stays honest as a contained pre-close review, not a broad permit-administration engagement.',
      why: 'Clear single-file deliverable with bounded review scope.',
    },
    {
      slug: 'budget-review',
      title: 'Budget & Scope Review',
      summary: 'A line-item audit of your existing budget and scope against current market costs. Works pre-purchase (validating a pro-forma) or post-purchase (before contractors price it or the lender sets the draw). You bring a budget — yours, an investor pro-forma, a contractor bid — and we pressure-test it.',
      pain: 'Your budget and scope have to survive contractor pricing and lender review — but they almost always have missing line items and numbers that are quietly off-market.',
      outcome: 'Get a bid-grade output: corrected line items, scope gaps filled, market-rate assumptions surfaced, and a budget you can confidently use for underwriting, contractor bids, or lender draws.',
      details: ['Line-by-line budget review', 'Scope gap analysis', 'Market-rate corrections', 'Missing scope items surfaced', 'Hidden-condition reserve recommendations'],
      included: ['Line-item budget audit', 'Scope gap callouts', 'Market-rate cost corrections', 'Recommended contingency + reserves', 'Bid-grade summary number'],
      notIncluded: ['Decision-grade range only — see Investor Deal & Scope Review (no spreadsheet input needed)', 'Budget built from scratch — see Contractor-Grade Budget', 'Guaranteed contractor bid', 'Unlimited revisions'],
      fit: 'Best when you already have a budget (yours, an investor pro-forma, or a contractor bid) and need it pressure-tested against real market costs.',
      purchaseType: 'fixed',
      primaryAction: 'buy',
      cta: 'Buy Now',
      detailHref: detailHref('investors', 'budget-review'),
      itemKey: 'budget-review',
      monthlyPrice: '$599',
      turnaround: 'Typical turnaround: 2 business days',
      proofTitle: 'Useful before bids and draws lock in the wrong numbers',
      proofBody: 'Line-item audit, not a vibes review. We catch the gaps you would otherwise discover mid-construction.',
      why: 'Owners need bid-grade precision — not just an opinion on whether to close.',
    },
    {
      slug: 'contractor-grade-budget',
      title: 'Contractor-Grade Budget',
      summary: 'We BUILD your project budget from scratch — takeoffs, real trade-network unit costs, written assumptions, and a bid-ready spreadsheet. The budget a GC would put together for the job, delivered without hiring one.',
      pain: 'You have plans or a clear scope but no real budget — and the spreadsheet you have was put together with vibes and Google searches.',
      outcome: 'Get a contractor-grade budget you can take straight to bids, lenders, or your underwriting model: line-item takeoffs, current market unit pricing, documented assumptions, and a clear total.',
      details: ['Full takeoffs (count, sqft, lf)', 'Line-item unit costs from current trade-network pricing', 'Written assumptions per major line', 'Soft-cost + contingency recommendations', 'Bid-ready spreadsheet output'],
      included: ['Plans/photo review', 'Full project takeoff', 'Line-item budget build', 'Documented assumptions', 'Bid-ready Excel deliverable'],
      notIncluded: ['Site walk (available as add-on)', 'Guaranteed contractor bid', 'Permit submission', 'Project management', 'Audit of someone else\'s budget — see Budget & Scope Review'],
      fit: 'Best when you have plans or a clear scope but no real budget yet, and you want the number a GC would put together — without the GC retainer.',
      purchaseType: 'fixed',
      primaryAction: 'buy',
      cta: 'Buy Now',
      detailHref: detailHref('investors', 'contractor-grade-budget'),
      itemKey: 'contractor-grade-budget',
      monthlyPrice: '$1,799',
      turnaround: 'Typical turnaround: 5 business days',
      proofTitle: 'Useful before contractors price the wrong scope',
      proofBody: 'A real budget — takeoffs and trade-priced — replaces the spreadsheet you would otherwise hand a contractor to mark up.',
      why: 'Some buyers need a budget built, not audited — this fills the gap between the $599 audit product and a full GC engagement.',
    },
    {
      slug: 'contractor-fit-consultation',
      title: 'Contractor Fit & Recommendation',
      summary: 'A paid consultation for investors who need to know what kinds of contractors this project actually needs — and why — before hiring conversations start.',
      pain: 'You do not want to start hiring against the wrong contractor mix and pay for it later.',
      outcome: 'Get a contractor-mix recommendation (which contractors, license levels, and specialties) with the reasoning behind each role.',
      details: ['Project review for contractor-mix fit', 'Recommended contractor mix (kinds, license levels, specialties)', 'Reasoning behind each role', 'Wrong-fit contractor types to avoid', 'Hiring direction for each role'],
      included: ['Consultation', 'Contractor-mix recommendation', 'Written reasoning per role', 'Wrong-fit callouts'],
      notIncluded: ['Comparing specific named contractors', 'Reviewing bids you have already received', 'Contractor sourcing or recruitment', 'Project management'],
      fit: 'Best when you are not sure whether you need a licensed GC, specialty subs, generalists, or a handyman — and in what combination — for this specific project.',
      purchaseType: 'fixed',
      primaryAction: 'buy',
      cta: 'Buy Now',
      detailHref: detailHref('investors', 'contractor-fit-consultation'),
      itemKey: 'contractor-fit-consultation',
      monthlyPrice: '$349',
      turnaround: 'Scheduled consultation',
      proofTitle: 'Useful before hiring against the wrong contractor mix',
      proofBody: 'This is a mix-and-reasoning product, not a bid review.',
      why: 'Knowing WHAT KINDS of contractors fit — and why — is a different decision from picking between named candidates.',
    },
  ],
  priced: [
    {
      slug: 'rent-ready-turn',
      title: 'Rent-Ready Turn',
      summary: 'A pricing-direction service for owners who need a clearer cost range on a vacant unit or turn before delay, rent loss, and scope creep get worse.',
      pain: 'You need a better turn number before approving the wrong path or losing more vacancy time.',
      outcome: 'Get turn pricing based on unit count, size, and condition inputs.',
      details: ['Unit-count review', 'Condition-based pricing range', 'Size assumptions', 'Summary of likely turn budget'],
      included: ['Pricing-direction review', 'Assumption notes', 'Turn range summary'],
      notIncluded: ['Guaranteed contractor quote', 'Full scope package'],
      fit: 'Best when you need a cleaner number on a turn before deciding how fast to move.',
      purchaseType: 'priced',
      primaryAction: 'pricing',
      cta: 'Enter Unit Details',
      detailHref: detailHref('investors', 'rent-ready-turn'),
      ctaHref: '/pricing/rent-ready-turn',
      pricingNote: 'Current calculator should route into a pricing page, not Add to Cart.',
      proofTitle: 'Useful before vacancy starts costing real money',
      proofBody: 'This is input-priced, not a fixed product.',
      why: 'Condition and size affect the number too much for product behavior.',
    },
    {
      slug: 'draw-review-support',
      title: 'Draw Review Support',
      summary: 'A fixed-price review service for investors who need a cleaner read on draw support before funding friction gets worse.',
      pain: 'You need a stronger read on scope, progress, and support material before a draw conversation goes sideways.',
      outcome: 'Get a structured review of what needs to be cleaned up before submission.',
      details: ['Draw support review', 'Scope and support check', 'Gap notes', 'Recommended next step'],
      included: ['Draw-support review', 'Gap notes', 'Recommendation'],
      notIncluded: ['Guaranteed lender approval', 'Unlimited revisions'],
      fit: 'Best when draw support needs to be tightened before it creates more delay.',
      purchaseType: 'fixed',
      primaryAction: 'buy',
      cta: 'Buy Now',
      detailHref: detailHref('investors', 'draw-review-support'),
      itemKey: 'draw-review-support',
      monthlyPrice: '$399',
      turnaround: 'Typical turnaround: 1 business day',
      proofTitle: 'Useful before draw issues slow funding',
      proofBody: 'This stays honest as a contained per-draw review with one clear deliverable.',
      why: 'Single draw review is a bounded service and can support real checkout behavior.',
    },
  ],
  review: [
    {
      slug: 'bid-coordination-contractor-match',
      title: 'Contractor Match & Bid Coordination',
      summary: 'We source vetted contractors that fit your scope, collect bids on a structured intake, level them against each other, and present the cleanest comparison — so the award decision is easier and you are not chasing random quotes.',
      pain: 'Random bids from random contractors create expensive startup mistakes — and chasing them down yourself eats time you do not have.',
      outcome: 'Get a structured contractor comparison: vetted candidates that fit your scope, leveled bids on the same line items, gap and risk notes, and a clear recommendation for who to award.',
      details: ['Scope-based contractor targeting', 'Outreach to vetted candidates', 'Structured bid intake (same line items)', 'Side-by-side leveling and comparison', 'Gap and risk notes per bid', 'Award recommendation'],
      included: ['Sourcing 3–5 contractor candidates per trade', 'Structured bid coordination', 'Leveled comparison', 'Risk and gap callouts', 'Written award recommendation'],
      notIncluded: ['Guaranteed contractor signing', 'Project management', 'Unlimited bid rounds'],
      fit: 'Best after you know what kinds of contractors you need (see Contractor Fit Consultation) and now want them sourced, bid, and leveled for you.',
      purchaseType: 'fixed',
      primaryAction: 'buy',
      cta: 'Buy Now',
      detailHref: detailHref('investors', 'bid-coordination-contractor-match'),
      itemKey: 'bid-coordination-contractor-match',
      monthlyPrice: '$1,499',
      turnaround: 'Typical turnaround: 7–10 business days',
      proofTitle: 'Useful when chasing your own contractor bids is costing you weeks',
      proofBody: 'Pairs cleanly after Contractor Fit Consultation — bundle the two and save $300.',
      why: 'Most investors lose more time on contractor sourcing than the price of this service.',
    },
    {
      slug: 'materials-logistics-setup',
      title: 'Materials Logistics Setup',
      summary: 'A setup service for investors who need purchasing, delivery timing, and material responsibility handled more cleanly before the job starts.',
      pain: 'Weak materials setup can create avoidable delay fast once work starts.',
      outcome: 'Start with a review so purchasing and delivery flow can be scoped correctly.',
      details: ['Materials responsibility review', 'Supplier and delivery flow planning', 'Ordering sequence guidance', 'Procurement workflow notes'],
      included: ['Initial setup review', 'Workflow recommendation', 'Next-step scope'],
      notIncluded: ['Full procurement management', 'Unlimited vendor coordination'],
      fit: 'Best when materials confusion could slow the job down quickly.',
      purchaseType: 'review',
      primaryAction: 'review',
      cta: 'Request Review',
      detailHref: detailHref('investors', 'materials-logistics-setup'),
      ctaHref: '/review/materials-logistics-setup',
      proofTitle: 'Useful before delivery mistakes slow the project',
      proofBody: 'Needs review first because workflow needs differ by project.',
      why: 'Project-specific setup work, not a commodity purchase.',
    },
    {
      slug: 'lender-scope-bid-package',
      title: 'Lender Scope & Bid Package',
      summary: 'A scope-of-work and bid package for investors who need numbers they can submit with more confidence to a lender or capital partner.',
      pain: 'Weak scope support creates funding friction and shaky lender conversations.',
      outcome: 'Start with a review so the package can be scoped around the actual project and lender need.',
      details: [
        'Project review tied to lender or capital-partner expectations',
        'Scope-of-work structure built around the actual job',
        'Bid-package planning so pricing conversations start from cleaner support',
        'Submission-readiness notes before the package goes out',
        'Review of current numbers, support docs, and gaps before submission',
        'Clearer package direction before bids or lender questions start dragging the file',
      ],
      included: [
        'Initial project and file review',
        'Recommendation on what the package needs to include',
        'Scope and bid-package planning discussion',
        'Guidance on what support material should be cleaned up first',
      ],
      notIncluded: ['Guaranteed lender acceptance', 'Universal flat-fee package'],
      fit: 'Best when lender-facing project support needs to be taken seriously.',
      purchaseType: 'review',
      primaryAction: 'review',
      cta: 'Request Review',
      detailHref: detailHref('investors', 'lender-scope-bid-package'),
      ctaHref: '/review/lender-scope-bid-package',
      nextStep:
        'Southern Cities reviews the project, the lender need, and the current support material, then outlines the right package structure before you move further into submission or bid collection.',
      proofTitle: 'Useful when your support docs need to look ready for capital',
      proofBody: 'This should sell like a serious decision page, not a cart item.',
      why: 'Higher-stakes deliverable with too much project-specific variance for ecommerce.',
    },
    {
      slug: 'regional-investor-setup-consultation',
      title: 'Regional Investor Setup Consultation',
      summary: 'A startup-focused review for operators entering a region or tightening a repeat model before avoidable startup mistakes show up.',
      pain: 'You do not want weak local setup to create avoidable execution mistakes after closing.',
      outcome: 'Start with a review so setup guidance is grounded in the market and project model.',
      details: ['Regional setup review', 'Contractor ecosystem considerations', 'Permit and process considerations', 'Mobilization-readiness guidance'],
      included: ['Initial setup review', 'Readiness notes', 'Next-step recommendation'],
      notIncluded: ['Turnkey local operations buildout', 'Unlimited contractor sourcing'],
      fit: 'Best when you are entering a region or tightening a repeat model.',
      purchaseType: 'review',
      primaryAction: 'review',
      cta: 'Request Setup Review',
      detailHref: detailHref('investors', 'regional-investor-setup-consultation'),
      ctaHref: '/review/regional-investor-setup-consultation',
      proofTitle: 'Useful before small setup mistakes turn into big ones',
      proofBody: 'This is strategic project setup support, not a product SKU.',
      why: 'Scoping depends on geography, model, and operational goals.',
    },
    {
      slug: 'construction-oversight',
      title: 'Construction Oversight',
      summary: 'Help for active investor projects that need tighter communication, stronger follow-through, and better accountability.',
      pain: 'The project is active and the risk is real, but the job still needs stronger control than it has now.',
      outcome: 'Start with a review so oversight scope fits the project risk and file condition.',
      details: ['Project review', 'Oversight scope', 'Milestone structure', 'Coordination support plan'],
      included: ['Initial review', 'Oversight recommendation', 'Scope discussion'],
      notIncluded: ['Flat-fee one-size-fits-all oversight package', 'Unlimited site support'],
      fit: 'Best when the project is active and tighter execution matters.',
      purchaseType: 'review',
      primaryAction: 'review',
      cta: 'Request Oversight Review',
      detailHref: detailHref('investors', 'construction-oversight'),
      ctaHref: '/review/construction-oversight',
      proofTitle: 'Useful when active projects need stronger control',
      proofBody: 'This should be scoped, not carted.',
      why: 'Active-job complexity is too variable for ecommerce treatment.',
    },
    {
      slug: 'contractor-scope-mapping',
      title: 'Contractor Scope Mapping',
      summary: 'A planning review that maps the trades and scope you actually need before contractor decisions move forward.',
      pain: 'Without a clear scope map, you end up hiring against assumptions instead of the actual work.',
      outcome: 'Start with a review so the trade list, scope breakdown, and contractor structure match the real project.',
      details: ['Project review for scope clarity', 'Trade-by-trade mapping', 'Scope-of-work breakdown', 'Contractor-structure recommendation'],
      included: ['Initial project review', 'Trade and scope map', 'Recommended contractor approach'],
      notIncluded: ['Contractor sourcing', 'Final scope-of-work drafting', 'Bid coordination'],
      fit: 'Best when you need to know WHAT trades are needed before figuring out WHO to hire.',
      purchaseType: 'review',
      primaryAction: 'review',
      cta: 'Request Review',
      detailHref: detailHref('investors', 'contractor-scope-mapping'),
      ctaHref: '/review/contractor-scope-mapping',
      proofTitle: 'Useful before contractor decisions start without a real scope map',
      proofBody: 'Scope mapping is a planning step, not a commodity.',
      why: 'WHAT trades you need is different from WHO you hire — and the wrong answer to either is expensive.',
    },
    {
      slug: 'scope-timeline-setup',
      title: 'Scope & Timeline Setup',
      summary: 'A planning review that ties scope, sequence, and timeline together before the project leaves the drawing board.',
      pain: 'Scope and schedule decisions get made separately, and the project pays for it later.',
      outcome: 'Start with a review so scope, sequence, and timeline align before construction commitments lock in.',
      details: ['Project review for scope and schedule', 'Sequence and dependency mapping', 'Timeline structure', 'Risk and float guidance'],
      included: ['Initial review', 'Scope-and-timeline recommendation', 'Sequencing notes'],
      notIncluded: ['Full project management', 'Permit prep', 'Daily scheduling'],
      fit: 'Best when scope and timeline are still loose and decisions are about to lock in.',
      purchaseType: 'review',
      primaryAction: 'review',
      cta: 'Request Review',
      detailHref: detailHref('investors', 'scope-timeline-setup'),
      ctaHref: '/review/scope-timeline-setup',
      proofTitle: 'Useful before scope and timeline calcify against each other',
      proofBody: 'Scope-and-timeline planning is iterative, not flat-priced.',
      why: 'Most schedule problems are scope problems decided too late.',
    },
    {
      slug: 'draw-strategy-alignment',
      title: 'Construction Draw Strategy & Alignment',
      summary: 'A funding-side review that aligns the draw schedule with scope, lender expectations, and real progress milestones.',
      pain: 'Misaligned draws create funding friction, contractor pressure, and money released against the wrong work.',
      outcome: 'Start with a review so the draw structure matches the scope, the lender, and the way the work actually progresses.',
      details: ['Draw schedule review', 'Lender alignment check', 'Progress-milestone structure', 'Release-criteria recommendations'],
      included: ['Initial review', 'Draw-schedule recommendation', 'Alignment notes'],
      notIncluded: ['Lender approval', 'Submitting draws on your behalf', 'Legal opinion'],
      fit: 'Best when draws are about to start and the schedule has not been pressure-tested yet.',
      purchaseType: 'review',
      primaryAction: 'review',
      cta: 'Request Review',
      detailHref: detailHref('investors', 'draw-strategy-alignment'),
      ctaHref: '/review/draw-strategy-alignment',
      proofTitle: 'Useful before draw releases get tied to the wrong milestones',
      proofBody: 'Draw strategy varies by lender, scope, and project complexity.',
      why: 'A misaligned draw schedule is a funding problem and a contractor-pressure problem at the same time.',
    },
    {
      slug: 'cashflow-planning',
      title: 'Cashflow Planning',
      summary: 'A funding-side review that builds a schedule of cashflows around the actual project plan, draw structure, and lender pressure points.',
      pain: 'Without a real cashflow plan, money runs out at the wrong stage or sits idle at the wrong time.',
      outcome: 'Start with a review so the cashflow schedule matches the real project and funding context.',
      details: ['Cashflow schedule review', 'Scope-to-funding alignment', 'Lender and capital-partner timing', 'Risk-buffer guidance'],
      included: ['Initial review', 'Cashflow-schedule recommendation', 'Funding-timing notes'],
      notIncluded: ['Bookkeeping or accounting', 'Tax planning', 'Lender approval'],
      fit: 'Best when the project funding plan still has gaps or assumptions you have not pressure-tested.',
      purchaseType: 'review',
      primaryAction: 'review',
      cta: 'Request Review',
      detailHref: detailHref('investors', 'cashflow-planning'),
      ctaHref: '/review/cashflow-planning',
      proofTitle: 'Useful before cashflow gaps stall an otherwise good project',
      proofBody: 'Cashflow planning is project-specific and lender-specific.',
      why: 'Money on the wrong schedule kills more projects than bad scope alone.',
    },
    {
      slug: 'owner-controlled-build',
      title: 'Owner-Controlled Build (GC-Led)',
      tag: 'Flagship',
      summary: 'Our flagship hybrid execution model — you stay the owner and PM; Southern Cities provides the GC structure, permit pulling, and execution controls.',
      pain: 'You want the upside of self-managing without giving up the legal and operational structure of a licensed GC.',
      outcome: 'Start with a review so the GC-led structure, permit responsibility, and control points fit the project.',
      details: ['Project review for GC-led fit', 'GC structure and permit responsibility', 'Execution-control framework', 'Owner/PM role definition'],
      included: ['Initial review', 'Hybrid-model structure', 'Execution-control plan', 'Permit-pulling scope'],
      notIncluded: ['Full PM outsourcing', 'Unlimited site presence', 'Construction without owner engagement'],
      fit: 'Best when you want to PM the build but need the GC license, structure, and controls behind you.',
      purchaseType: 'review',
      primaryAction: 'review',
      cta: 'See If It Fits',
      detailHref: detailHref('investors', 'owner-controlled-build'),
      ctaHref: '/review/owner-controlled-build',
      proofTitle: 'Useful when neither full-DIY nor full-GC fits the project',
      proofBody: 'Hybrid execution is structured, not commoditized — it has to fit your specific project.',
      why: 'Most upside of self-managing, none of the unlicensed-execution risk.',
    },
    {
      slug: 'project-coordination-control',
      title: 'Project Coordination & Control',
      summary: 'An execution-support service that adds coordination, control, and follow-through to active projects without taking over full management.',
      pain: 'The project is active but coordination is loose — meetings slip, decisions stall, follow-up disappears.',
      outcome: 'Start with a review so coordination scope and control points match the project size and pace.',
      details: ['Project review for coordination needs', 'Control-point identification', 'Meeting and reporting structure', 'Follow-through ownership'],
      included: ['Initial review', 'Coordination scope', 'Reporting cadence recommendation'],
      notIncluded: ['Full project management', 'Unlimited site presence', 'Owner-side decision authority'],
      fit: 'Best when execution is happening but coordination is the weak link.',
      purchaseType: 'review',
      primaryAction: 'review',
      cta: 'Request Review',
      detailHref: detailHref('investors', 'project-coordination-control'),
      ctaHref: '/review/project-coordination-control',
      proofTitle: 'Useful when the project is active but the controls are loose',
      proofBody: 'Coordination-and-control work is project-specific.',
      why: 'A coordinated project finishes; an uncoordinated one drifts.',
    },
    {
      slug: 'full-construction-management',
      title: 'Full Construction Management Service',
      summary: 'Full-service construction management for investor projects that need a single accountable team running the entire build.',
      pain: 'Loose coordination, missed milestones, and unclear ownership are slowing the project and the margin.',
      outcome: 'Start with a review so a full-CM engagement is sized and scoped against the actual project.',
      details: ['Project review for CM fit', 'Scope, schedule, and budget management', 'Permit pulling and admin', 'Subcontractor coordination', 'Draw and reporting cadence'],
      included: ['Initial review', 'CM scope and pricing structure', 'Engagement plan'],
      notIncluded: ['Flat-fee CM without project review', 'Owner-side capital deployment'],
      fit: 'Best when the project is large or complex enough that one accountable team should run all of it.',
      purchaseType: 'review',
      primaryAction: 'review',
      cta: 'Request Review',
      detailHref: detailHref('investors', 'full-construction-management'),
      ctaHref: '/review/full-construction-management',
      proofTitle: 'Useful when one accountable team should run the entire build',
      proofBody: 'Full CM scopes need a project review before pricing.',
      why: 'The right CM structure depends on scope, location, and operator capacity.',
    },
  ],
  recurringIntro:
    'If the same delays, budget questions, follow-up problems, and active-file decisions keep coming back, Southern Cities also offers capped monthly plans for repeat investor work.',
  recurring: [
    {
      slug: 'turn-support-plan',
      title: 'Turn Support Plan',
      tag: 'Entry plan',
      summary: 'Monthly support for owners with recurring turns and routine project decisions that keep pulling attention away from the rest of the business.',
      pain: 'Repeated turn decisions and vacancy drag keep eating time and margin.',
      outcome: 'Get ongoing monthly support for recurring turn reviews and budget questions.',
      details: ['Up to 2 project decision reviews each month, each covering 1 property turn, rehab file, or active project decision set', 'Up to 2 budget or scope reviews each month, each covering 1 estimate, scope draft, or bid set', 'Basic permit and admin guidance on active files', 'Priority response during business hours'],
      included: ['Defined monthly review capacity with each review type spelled out', 'Priority response window', 'Recurring support scope'],
      notIncluded: ['Unlimited reviews', 'Site visits', 'Full project management'],
      fit: 'Best when recurring turns keep eating time and margin across repeat files.',
      purchaseType: 'recurring',
      primaryAction: 'plan',
      cta: 'Review Plan',
      detailHref: detailHref('investors', 'turn-support-plan'),
      ctaHref: '/recurring-support#investors',
      monthlyPrice: '$749/mo',
      monthlyLimit: 'Up to 2 reviews and up to 3 active properties',
      turnaround: '1 business day response target',
      proofTitle: 'Useful when the same turn issues keep repeating',
      proofBody: 'This is ongoing monthly support, not a one-off service.',
      why: 'Clear recurring pain and defined monthly usage cap.',
    },
    {
      slug: 'operator-support-plan',
      title: 'Operator Support Plan',
      tag: 'Most practical',
      summary: 'A stronger recurring support plan for investors who need more frequent pricing help, lender support, and better follow-through on active work.',
      pain: 'Delay, funding friction, and repeated owner follow-up are dragging active projects down.',
      outcome: 'Get ongoing monthly support with clearly defined review capacity and stronger active-project help.',
      details: ['Up to 4 project decision reviews each month, each covering 1 turn file, rehab file, or active project decision set', 'Up to 4 budget or scope reviews each month, each covering 1 estimate, scope draft, or bid set', '1 lender scope and bid package each month, meaning 1 compiled lender-facing scope package for 1 property or project', '1 draw review support item each month, meaning 1 draw request review with supporting notes for 1 submission cycle'],
      included: ['Defined monthly support volume', 'Lender/draw support cap', 'Priority response window'],
      notIncluded: ['Unlimited support', 'On-site management', 'Open-ended custom work'],
      fit: 'Best when active jobs need recurring support across multiple files.',
      purchaseType: 'recurring',
      primaryAction: 'plan',
      cta: 'Review Plan',
      detailHref: detailHref('investors', 'operator-support-plan'),
      ctaHref: '/recurring-support#investors',
      monthlyPrice: '$1,499/mo',
      monthlyLimit: '4 reviews, 1 lender package, 1 draw item',
      turnaround: 'Same-day acknowledgment, 1 business day standard response',
      proofTitle: 'Useful when the same investor questions keep repeating',
      proofBody: 'This is one of the strongest recurring offers on the site.',
      why: 'Clear recurring pain and defined deliverable cap.',
    },
    {
      slug: 'project-support-retainer',
      title: 'Project Support Retainer',
      tag: 'Higher-touch',
      summary: 'A retainer for higher-volume operators who need weekly oversight, repeated project review, and steady follow-through across active jobs.',
      pain: 'Too many active files and too much owner involvement are making live jobs harder to manage.',
      outcome: 'Start with a retainer review so monthly support is scoped to the actual operator load.',
      details: ['Weekly project-control touchpoint', 'Up to 6 project decision reviews each month, each covering 1 active project issue, milestone decision, or control review', 'Up to 6 budget or scope reviews each month, each covering 1 estimate, scope revision, or change decision', 'Up to 2 lender or draw support items each month, each meaning either 1 lender package review or 1 draw-submission review'],
      included: ['Defined retainer framework', 'Priority response target', 'Capped support volume'],
      notIncluded: ['Unlimited support', 'Unscoped site visits', 'Open-ended ops outsourcing'],
      fit: 'Best when active projects and repeated owner involvement need higher-touch ongoing support.',
      purchaseType: 'recurring',
      primaryAction: 'plan',
      cta: 'Request Retainer Review',
      detailHref: detailHref('investors', 'project-support-retainer'),
      ctaHref: '/recurring-support#investors',
      monthlyPrice: 'Starting at $2,500/mo',
      monthlyLimit: 'Capped support volume, site visits separate',
      turnaround: 'Priority 24-hour response target',
      proofTitle: 'Useful when ongoing support needs to match a heavier project load',
      proofBody: 'Higher-touch retainers should start with review, not checkout.',
      why: 'Retainer scope depends on operator volume and live-file complexity.',
    },
    {
      slug: 'due-diligence-package',
      title: 'Due Diligence Package',
      tag: 'Recurring',
      summary: 'A monthly package for investors evaluating 2–3 deals per month who need consistent licensed-GC review before committing.',
      pain: 'Deal flow is real, but one-off reviews are expensive and slow when the pipeline is steady.',
      outcome: 'Get capped-volume due-diligence review built around your deal pace.',
      details: ['Up to 3 deal reviews per month', 'Investor Deal & Scope Review covered', 'Budget validation included', 'Permit-path read included', 'Written review per deal', 'Priority response on active deals'],
      included: ['Defined monthly review cap', 'Standard 2-day turnaround per deal', 'Email follow-up'],
      notIncluded: ['Unlimited reviews', 'Permit filing', 'Contractor sourcing'],
      fit: 'Best for investors with consistent deal flow who want pre-buy review built into the workflow.',
      purchaseType: 'recurring',
      primaryAction: 'plan',
      cta: 'Review Plan',
      detailHref: detailHref('investors', 'due-diligence-package'),
      ctaHref: '/recurring-support#investors',
      monthlyPrice: '$1,250/mo',
      monthlyLimit: 'Up to 3 deal reviews per month with 2-business-day turnaround',
      turnaround: '2 business days per deal',
      proofTitle: 'Useful when deal flow is steady and one-off reviews start adding up',
      proofBody: 'The package fits investors running multiple deals through the same gate.',
      why: 'Consistent volume should not require consistently buying one-offs.',
    },
    {
      slug: 'construction-planning-package',
      title: 'Construction Planning Package',
      tag: 'Recurring',
      summary: 'A monthly package for investors planning 2–3 active projects who need consistent setup support before construction starts.',
      pain: 'Project planning is repeating itself across multiple projects and each setup is starting from scratch.',
      outcome: 'Get capped-volume planning support built around your project pipeline.',
      details: ['Up to 3 project planning engagements per month', 'Scope mapping included', 'Bid coordination support', 'Permit prep guidance', 'Timeline and materials setup', 'Written setup per project'],
      included: ['Defined monthly capacity', 'Standard turnaround per project', 'Email follow-up'],
      notIncluded: ['Active project management', 'Full construction execution', 'Unlimited project capacity'],
      fit: 'Best for investors running multiple projects through the same setup gate each month.',
      purchaseType: 'recurring',
      primaryAction: 'plan',
      cta: 'Review Plan',
      detailHref: detailHref('investors', 'construction-planning-package'),
      ctaHref: '/recurring-support#investors',
      monthlyPrice: '$1,750/mo',
      monthlyLimit: 'Up to 3 project planning engagements per month',
      turnaround: '3 business days per project',
      proofTitle: 'Useful when the same setup work repeats across active projects',
      proofBody: 'Recurring planning makes sense when the volume is consistent.',
      why: 'Per-project setup compounds — recurring support is more efficient and more accurate.',
    },
  ],
};

const realtorServices: AvatarPageData = {
  slug: 'realtors',
  eyebrow: 'Realtors',
  shortLabel: 'For Realtors',
  heroTitle: 'Construction help for realtors before listing work gets messy and when active deals need faster answers',
  heroSubtitle:
    'Southern Cities helps realtors get faster repair direction, clearer listing-prep answers, and practical construction guidance before deals, listings, and client confidence start slipping.',
  painPoints: [
    'Inspection reports are creating confusion.',
    'Repair questions are delaying client decisions.',
    'Listing prep needs clearer scope and timing.',
    'Client confidence drops when no one can explain the work simply.',
  ],
  outcomes: [
    'Faster answers on repair and construction questions.',
    'Clearer repair path and listing prep direction.',
    'Stronger client confidence.',
    'Better transaction and listing momentum.',
  ],
  fixed: [
    {
      slug: 'inspection-response',
      title: 'Inspection Response',
      summary: 'A fast review of inspection items so the real issues, likely scope, and next step are easier to understand.',
      pain: 'The deal needs clearer construction guidance quickly.',
      outcome: 'Get a fast repair-priority read and clearer next-step direction.',
      details: ['Inspection issue review', 'Priority breakdown', 'Repair-scope guidance', 'Clear response path'],
      included: ['Inspection review', 'Priority notes', 'Response-path guidance'],
      notIncluded: ['Full repair coordination', 'Listing-prep management'],
      fit: 'Best when the deal needs clearer construction guidance quickly.',
      purchaseType: 'fixed',
      primaryAction: 'buy',
      cta: 'Buy Now',
      detailHref: detailHref('realtors', 'inspection-response'),
      itemKey: 'inspection-response-service',
      monthlyPrice: '$299 assessment',
      turnaround: 'Typical turnaround: 1 business day',
      proofTitle: 'Useful when inspection questions are slowing the deal',
      proofBody: 'This is a clean, urgent starter offer that fits product behavior well.',
      why: 'Clear deliverable, fast turnaround, strong fixed-price fit.',
    },
    {
      slug: 'realtor-inspection-review',
      title: 'Realtor Inspection Review',
      summary: 'A focused review for agents who need a practical read on repair scope before conversations go sideways.',
      pain: 'You need a clearer construction read before client conversations get messy.',
      outcome: 'Get a cleaner explanation of what matters and what the next move should be.',
      details: ['Inspection report review', 'Repair-path guidance', 'Priority notes', 'Next-step recommendation'],
      included: ['Inspection review', 'Repair-path notes', 'Decision guidance'],
      notIncluded: ['Listing-prep coordination', 'Contractor management'],
      fit: 'Best when the agent needs a more explicit construction read for client communication.',
      purchaseType: 'fixed',
      primaryAction: 'buy',
      cta: 'Buy Now',
      detailHref: detailHref('realtors', 'realtor-inspection-review'),
      itemKey: 'realtor-inspection-review',
      monthlyPrice: '$299 review',
      turnaround: 'Typical turnaround: 1 business day',
      proofTitle: 'Useful when the agent needs answers fast',
      proofBody: 'Should stay distinct from broader coordination work.',
      why: 'Contained deliverable with clear value and fast urgency.',
    },
  ],
  priced: [
    {
      slug: 'pre-listing-budget-prep-review',
      title: 'Pre-Listing Work',
      summary: 'A clearer read on what should be fixed, what can be skipped, and what prep budget range makes sense before a listing goes live.',
      pain: 'You need better prep decisions before seller hesitation and guesswork create drag.',
      outcome: 'Get property-specific pricing direction and prep guidance before work is coordinated.',
      details: ['Scope review', 'Prep-priority guidance', 'Likely budget range', 'Timeline notes tied to listing goals'],
      included: ['Prep review', 'Budget-direction guidance', 'Priority notes'],
      notIncluded: ['Guaranteed contractor quote', 'Listing-prep project management'],
      fit: 'Best when presentation and timing matter, but you need cleaner direction first.',
      purchaseType: 'priced',
      primaryAction: 'pricing',
      cta: 'Enter Property Details',
      detailHref: detailHref('realtors', 'pre-listing-work'),
      ctaHref: '/pricing/pre-listing-budget-prep-review',
      pricingNote: 'Current calculator should route to pricing review, not cart.',
      proofTitle: 'Useful before sellers start spending in the wrong places',
      proofBody: 'A real prep review tied to the listing, not a one-click cart purchase.',
      why: 'Property size, condition, and occupancy affect the pricing direction.',
    },
  ],
  review: [
    {
      slug: 'listing-prep-coordination',
      title: 'Listing Prep Coordination',
      summary: 'Review-first help for listings that need broader prep coordination before they are ready to go live.',
      pain: 'The property needs more than a quick answer and real coordination will likely be needed.',
      outcome: 'Start with a review so listing prep can be scoped cleanly before coordination begins.',
      details: ['Property review', 'Scope planning', 'Coordination plan', 'Quote path based on the work involved'],
      included: ['Initial review', 'Coordination recommendation', 'Next-step scope'],
      notIncluded: ['Flat-fee universal listing-prep package', 'Unlimited coordination'],
      fit: 'Best when the property needs more than a quick repair answer.',
      purchaseType: 'review',
      primaryAction: 'review',
      cta: 'Request Listing Prep Review',
      detailHref: detailHref('realtors', 'listing-prep-coordination'),
      ctaHref: '/review/listing-prep-coordination',
      proofTitle: 'Useful when listing prep needs to be scoped properly',
      proofBody: 'This is coordination work and should not be treated like a product.',
      why: 'Scope varies too much to price casually or cart honestly.',
    },
  ],
  recurringIntro:
    'If inspection questions, listing-prep indecision, and repeated client repair questions keep eating time, these monthly plans give you a defined way to get answers faster without starting from scratch every time.',
  recurring: [
    {
      slug: 'deal-desk',
      title: 'Deal Desk',
      tag: 'Main offer',
      summary: 'Recurring support for active deals that need faster repair direction and inspection answers before the deal starts dragging.',
      pain: 'Inspection issues and repair questions keep slowing deals down and making client conversations harder.',
      outcome: 'Get ongoing monthly support for active-deal guidance and repair direction.',
      details: ['Up to 4 active deal reviews each month, each covering 1 inspection, repair, or deal-side construction decision file', 'Inspection report review and repair-priority guidance', 'Up to 2 rough pricing-direction requests each month', 'Written summaries for client conversations'],
      included: ['Defined monthly review capacity with each review type spelled out', 'Pricing-direction cap with each request defined as one property-level pricing question', 'Written deal-support summaries'],
      notIncluded: ['Unlimited agent support', 'Listing coordination'],
      fit: 'Best when active deals need repeated repair guidance every month.',
      purchaseType: 'recurring',
      primaryAction: 'plan',
      cta: 'Review Plan',
      detailHref: detailHref('realtors', 'deal-desk'),
      ctaHref: '/recurring-support#realtors',
      monthlyPrice: '$649/mo',
      monthlyLimit: 'Up to 4 deal files and 2 property-level pricing-direction requests each month',
      turnaround: '1 business day response, same-day triage target on urgent items',
      proofTitle: 'Useful when inspection and repair questions keep coming up',
      proofBody: 'Good recurring fit because the same problem keeps coming back.',
      why: 'Clear recurring pain with defined usage cap.',
    },
    {
      slug: 'listing-prep-desk',
      title: 'Listing Prep Desk',
      tag: 'Main offer',
      summary: 'Monthly support for agents who repeatedly need better pre-listing repair direction before seller indecision turns into delay.',
      pain: 'Sellers keep going back and forth on what to fix, what to skip, and what is worth spending on.',
      outcome: 'Get ongoing monthly support for listing prep direction before listings go live.',
      details: ['Up to 4 listing-prep reviews each month, each covering 1 property prep decision set before listing', 'Repair vs leave-alone guidance', 'Prep-priority and sequencing notes', 'Up to 2 follow-up clarifications per property'],
      included: ['Defined monthly prep-review capacity with each property counted separately', 'Clarification cap with each follow-up defined as a short post-review question', 'Recurring prep guidance'],
      notIncluded: ['Unlimited seller consulting', 'Full prep coordination'],
      fit: 'Best when listing-prep indecision keeps showing up across active files.',
      purchaseType: 'recurring',
      primaryAction: 'plan',
      cta: 'Review Plan',
      detailHref: detailHref('realtors', 'listing-prep-desk'),
      ctaHref: '/recurring-support#realtors',
      monthlyPrice: '$649/mo',
      monthlyLimit: 'Up to 4 listing-prep files each month plus up to 2 short follow-up clarifications per property',
      turnaround: '1 business day first response, 2 business day standard delivery',
      proofTitle: 'Useful when listing-prep questions keep coming up',
      proofBody: 'This is recurring guidance, not a one-off service.',
      why: 'Clear recurring use case with defined support caps.',
    },
  ],
};

const contractorServices: AvatarPageData = {
  slug: 'contractors',
  eyebrow: 'Contractors',
  shortLabel: 'For Contractors',
  heroTitle: 'Permit and back-office help for contractors who need cleaner setup and less admin drag on active jobs',
  heroSubtitle:
    'Southern Cities helps contractors reduce paperwork drag, inspection delays, correction follow-up, and coordination burden without hiring full-time office staff.',
  painPoints: [
    'Permit paperwork keeps slowing production down.',
    'Inspection follow-up keeps pulling attention off the field.',
    'Correction handling gets dropped or delayed.',
    'The office side is too thin for the job load.',
  ],
  outcomes: [
    'Less paperwork drag and more time for production.',
    'Cleaner permit handling and better inspection follow-through.',
    'More office support without full-time payroll.',
    'Better coordination when active jobs start feeling stretched.',
  ],
  priced: [
    {
      slug: 'permit-administration',
      title: 'Permit Administration',
      summary: 'Permit help for contractors and trade teams that want paperwork handled more cleanly.',
      pain: 'Your team should be focused on the field, not buried in permit follow-up.',
      outcome: 'Start pricing review for permit support based on job type, jurisdiction, and file condition.',
      details: ['Permit application prep', 'Submission follow-up', 'Correction handling', 'Inspection scheduling support'],
      included: ['Permit-support review', 'Likely support scope', 'Pricing path based on file needs'],
      notIncluded: ['Universal flat-fee permit service', 'Unlimited jurisdictions'],
      fit: 'Best when the field should not be carrying office paperwork.',
      purchaseType: 'priced',
      primaryAction: 'pricing',
      cta: 'Start Pricing Review',
      detailHref: detailHref('contractors', 'permit-administration'),
      ctaHref: '/pricing/permit-administration',
      proofTitle: 'Useful when permit work needs real follow-through',
      proofBody: 'This can be priced from a few inputs, but it should not be carted like a product.',
      why: 'Job type and jurisdiction affect scope enough to require pricing review.',
    },
    {
      slug: 'inspection-scheduling-support',
      title: 'Inspection Scheduling Support',
      summary: 'Support for contractors who need inspections lined up, tracked, and followed through without extra back-and-forth.',
      pain: 'Inspection handling keeps pulling attention off production.',
      outcome: 'Get pricing based on job count, support level, and coordination needs.',
      details: ['Inspection scheduling', 'Follow-up coordination', 'Correction tracking', 'Status updates'],
      included: ['Inspection-support review', 'Coordination scope', 'Pricing path'],
      notIncluded: ['Unlimited inspection handling', 'Project management'],
      fit: 'Best when inspection handling keeps disrupting field time.',
      purchaseType: 'priced',
      primaryAction: 'pricing',
      cta: 'Get Pricing',
      detailHref: detailHref('contractors', 'inspection-scheduling-support'),
      ctaHref: '/pricing/inspection-scheduling-support',
      proofTitle: 'Useful when inspection follow-up is pulling crews off the job',
      proofBody: 'This should price from a few job inputs, not go through cart.',
      why: 'Job load and frequency affect scope.',
    },
  ],
  review: [
    {
      slug: 'admin-support-for-active-jobs',
      title: 'Admin Support for Active Jobs',
      summary: 'Back-office review support for contractors who need help sorting paperwork, follow-up, and coordination gaps on live residential work.',
      pain: 'The job load is outgrowing the office support behind it.',
      outcome: 'Start with a review so the admin support scope matches the actual backlog and job load.',
      details: ['Admin task review', 'Coordination support', 'Documentation follow-up', 'Clear next-step support'],
      included: ['Initial review', 'Support recommendation', 'Next-step scope'],
      notIncluded: ['Unlimited office outsourcing', 'Flat-fee admin package for all contractors'],
      fit: 'Best when office strain is already hurting execution.',
      purchaseType: 'review',
      primaryAction: 'review',
      cta: 'Request Admin Review',
      detailHref: detailHref('contractors', 'admin-support-for-active-jobs'),
      ctaHref: '/review/admin-support-for-active-jobs',
      proofTitle: 'Useful when back-office work is already overloaded',
      proofBody: 'This should also act as an upsell path into recurring support.',
      why: 'Needs scoping based on workload, backlog, and active job count.',
    },
    {
      slug: 'construction-oversight-support',
      title: 'Construction Oversight Support',
      summary: 'Help for contractors who need tighter coordination around milestones, updates, and project follow-through.',
      pain: 'Project control issues are starting to affect production.',
      outcome: 'Start with a review so oversight support matches the job condition and control need.',
      details: ['Project review', 'Support scope', 'Milestone structure', 'Coordination support plan'],
      included: ['Initial review', 'Oversight recommendation', 'Scope discussion'],
      notIncluded: ['Universal oversight package', 'Unlimited site support'],
      fit: 'Best when active jobs need stronger control than the team currently has.',
      purchaseType: 'review',
      primaryAction: 'review',
      cta: 'Request Oversight Review',
      detailHref: detailHref('contractors', 'construction-oversight-support'),
      ctaHref: '/review/construction-oversight-support',
      proofTitle: 'Useful when active job support needs to match the real workload',
      proofBody: 'This is too variable for product or pricing-page behavior.',
      why: 'Support scope depends on active-job condition and milestone risk.',
    },
  ],
  recurringIntro:
    'For contractors, monthly support makes sense when the same permit, inspection, and paperwork problems keep coming back across active jobs.',
  recurring: [
    {
      slug: 'permit-inspection-support-plan',
      title: 'Permit & Inspection Support Plan',
      tag: 'Entry plan',
      summary: 'Monthly support for contractors who need permit follow-up, inspection scheduling, and correction handling taken off their plate.',
      pain: 'Office work keeps pulling time away from production and slowing jobs down.',
      outcome: 'Get ongoing monthly support for recurring permit and inspection help.',
      details: ['Up to 4 permit or admin requests each month, each meaning 1 permit filing task, correction response, inspection scheduling task, or status follow-up sequence', 'Inspection scheduling support', 'Correction follow-up support', 'Permit status coordination on active files'],
      included: ['Defined request cap', 'Recurring permit and inspection help', 'Priority response window'],
      notIncluded: ['Unlimited active jobs', 'Full PM services'],
      fit: 'Best when the same office-side friction keeps coming back.',
      purchaseType: 'recurring',
      primaryAction: 'plan',
      cta: 'Review Plan',
      detailHref: detailHref('contractors', 'permit-inspection-support-plan'),
      ctaHref: '/recurring-support#contractors',
      monthlyPrice: '$899/mo',
      monthlyLimit: '4 requests and up to 2 active jobs',
      turnaround: '1 business day response target',
      proofTitle: 'Useful when permit and inspection admin keep repeating every month',
      proofBody: 'Good recurring fit because the same burden keeps returning.',
      why: 'Defined recurring pain and clear volume cap.',
    },
    {
      slug: 'back-office-support-plan',
      title: 'Back-Office Support Plan',
      tag: 'Strongest recurring fit',
      summary: 'A broader monthly support plan for contractors who need recurring help with admin, follow-up, documentation, and coordination across active residential jobs.',
      pain: 'Back-office overload is choking field production and forcing the owner to carry too much admin personally.',
      outcome: 'Get ongoing monthly support for the office-side work that keeps repeating across active jobs.',
      details: ['Up to 8 support requests each month, each meaning 1 clearly scoped admin, permit, inspection, or documentation task', 'Permit and admin support', 'Inspection coordination', 'Documentation and follow-up support'],
      included: ['Defined request cap', 'Recurring office support', 'Priority response window'],
      notIncluded: ['Unlimited admin support', 'Uncapped project load'],
      fit: 'Best when the contractor needs a real office extension without hiring full-time first.',
      purchaseType: 'recurring',
      primaryAction: 'plan',
      cta: 'Review Plan',
      detailHref: detailHref('contractors', 'back-office-support-plan'),
      ctaHref: '/recurring-support#contractors',
      monthlyPrice: '$1,750/mo',
      monthlyLimit: '8 requests and up to 4 active jobs',
      turnaround: 'Same-day acknowledgment, 1 business day standard response',
      proofTitle: 'Useful when office overload keeps slowing your team down',
      proofBody: 'One of the strongest recurring offers on the site.',
      why: 'Very clear recurring use case with strong commercial logic.',
    },
    {
      slug: 'contractor-office-extension-retainer',
      title: 'Contractor Office Extension Retainer',
      tag: 'Higher-touch',
      summary: 'A retainer for busy contractors who need steadier outside office help without building a full internal admin team yet.',
      pain: 'Hiring pressure, admin chaos, and revenue-producing field time are all getting squeezed by office problems.',
      outcome: 'Start with a retainer review so the support is scoped to your real job load.',
      details: ['Weekly check-in', 'Up to 12 support requests each month, each meaning 1 clearly scoped admin, permit, inspection, or documentation task', 'Priority permit and inspection coordination', 'Documentation and follow-up support across active jobs'],
      included: ['Retainer framework', 'Priority response target', 'Defined support cap'],
      notIncluded: ['Unlimited office outsourcing', 'Open-ended labor'],
      fit: 'Best when the contractor needs higher-touch outside office support.',
      purchaseType: 'recurring',
      primaryAction: 'plan',
      cta: 'Request Retainer Review',
      detailHref: detailHref('contractors', 'contractor-office-extension-retainer'),
      ctaHref: '/recurring-support#contractors',
      monthlyPrice: 'Starting at $2,900/mo',
      monthlyLimit: 'Defined active-job cap with 12 clearly scoped support tasks each month, not unlimited work',
      turnaround: 'Priority 24-hour response target',
      proofTitle: 'Useful when ongoing support needs to match a heavier workload',
      proofBody: 'Retainers should start with review, not checkout.',
      why: 'Higher-touch recurring support requires scoped review first.',
    },
  ],
};

const developerServices: AvatarPageData = {
  slug: 'developers-landowners',
  eyebrow: 'Developers / Landowners',
  shortLabel: 'For Developers / Landowners',
  heroTitle: 'Project help for larger residential work where early decisions and active-job discipline both matter',
  heroSubtitle:
    'Southern Cities helps developers, landowners, and repeat operators get a better early read on scope and budget, cleaner permit thinking, and steadier coordination once active residential work is underway.',
  painPoints: [
    'The early read on scope, permits, or budget still feels loose.',
    'Bigger money decisions need better pressure-testing first.',
    'Coordination and follow-through need to be tighter on active work.',
    'Active projects keep forcing late decisions and last-minute follow-up.',
  ],
  outcomes: [
    'A better early read before commitment.',
    'More realistic scope and budget thinking.',
    'Better coordination and steadier follow-through.',
    'Cleaner follow-through on active residential work.',
  ],
  review: [
    {
      slug: 'project-review',
      title: 'Project Review',
      summary: 'An early review for larger residential projects that need a clearer read on scope, permits, and execution before moving further.',
      pain: 'You need a stronger early read before bigger money moves in the wrong direction.',
      outcome: 'Start with a project review so the next step is grounded in a better understanding of risk and setup.',
      details: ['Project review', 'Permit-path observations', 'Risk notes', 'Recommended next step'],
      included: ['Early project review', 'Risk notes', 'Next-step guidance'],
      notIncluded: ['Guaranteed execution plan', 'Full oversight package'],
      fit: 'Best when you need an informed read before the project gets further into motion.',
      purchaseType: 'review',
      primaryAction: 'review',
      cta: 'Request Project Review',
      detailHref: detailHref('developers-landowners', 'project-review'),
      ctaHref: '/review/project-review',
      proofTitle: 'Useful before bigger money decisions get committed',
      proofBody: 'This can double as a landing page now because the use case is clear and high-intent.',
      why: 'High-value early-stage review with strong buyer intent but variable scope.',
    },
    {
      slug: 'budget-scope-review',
      title: 'Budget & Scope Review',
      summary: 'A clearer look at likely scope and cost before larger residential work starts getting more expensive than it should be.',
      pain: 'You need better early visibility into scope and cost before moving too casually.',
      outcome: 'Start with a review so budget and scope assumptions can be pressure-tested first.',
      details: ['Scope review', 'Budget observations', 'Visible assumptions', 'Cost-risk notes'],
      included: ['Budget/scope review', 'Assumption notes', 'Risk observations'],
      notIncluded: ['Guaranteed contractor bid', 'Detailed GMP proposal'],
      fit: 'Best when you need better early visibility into cost and scope.',
      purchaseType: 'review',
      primaryAction: 'review',
      cta: 'Request Budget Review',
      detailHref: detailHref('developers-landowners', 'budget-scope-review'),
      ctaHref: '/review/budget-scope-review',
      proofTitle: 'Useful before loose assumptions cost real money',
      proofBody: 'Larger projects should not be pushed into fake instant pricing.',
      why: 'High-stakes project variance makes pricing too sensitive for generic forms right now.',
    },
    {
      slug: 'permit-administration-construction-oversight',
      title: 'Permit Administration + Construction Oversight',
      summary: 'Help for larger residential projects that need tighter permit handling, job follow-through, and execution.',
      pain: 'The project is too important to run loosely once execution begins.',
      outcome: 'Start with a review so permit and oversight scope can be set responsibly.',
      details: ['Project review', 'Permit path planning', 'Oversight scope', 'Execution support around milestones and coordination'],
      included: ['Initial review', 'Scope discussion', 'Next-step recommendation'],
      notIncluded: ['Flat-fee universal flagship service', 'Unscoped oversight'],
      fit: 'Best when larger residential work needs tighter control around permits and execution.',
      purchaseType: 'review',
      primaryAction: 'review',
      cta: 'Request Project Review',
      detailHref: detailHref('developers-landowners', 'permit-administration-construction-oversight'),
      ctaHref: '/review/permit-administration-construction-oversight',
      proofTitle: 'Useful when permit handling and project execution both matter',
      proofBody: 'Real scoped support tied to the project, not a one-size-fits-all cart purchase.',
      why: 'High-stakes hybrid service with too much scope variance for checkout.',
    },
  ],
  recurringIntro:
    'For repeat operators, monthly support makes sense when delay and repeated follow-up keep showing up across multiple projects.',
  recurring: [
    {
      slug: 'project-control-plan',
      title: 'Project Control Plan',
      tag: 'Entry plan',
      summary: 'Monthly support for repeat operators who need a better read on active projects, upcoming risks, and the next decision that matters.',
      pain: 'Active projects keep needing repeated follow-up because accountability and visibility are weak.',
      outcome: 'Get ongoing project-control support with clearly defined project-status review capacity and clearer risk visibility.',
      details: ['Up to 2 active project reviews each month, each covering 1 project status review with milestone, risk, and next-step guidance', 'Milestone check-ins', 'Permit-path and coordination guidance', 'Risk and next-step summaries'],
      included: ['Defined monthly review cap', 'Milestone check-ins', 'Recurring project-control guidance'],
      notIncluded: ['Unlimited active projects', 'Full PM outsourcing'],
      fit: 'Best when repeat operators need a steadier read across active files.',
      purchaseType: 'recurring',
      primaryAction: 'plan',
      cta: 'Review Plan',
      detailHref: detailHref('developers-landowners', 'project-control-plan'),
      ctaHref: '/recurring-support#developers',
      monthlyPrice: '$1,250/mo',
      monthlyLimit: 'Support across up to 2 active projects plus up to 2 formal project-status reviews each month',
      turnaround: '1 business day response target',
      proofTitle: 'Useful when the same project gaps keep repeating',
      proofBody: 'Recurring support makes sense when the same visibility problem keeps coming back.',
      why: 'Clear recurring operational pain with defined monthly caps.',
    },
    {
      slug: 'execution-oversight-retainer',
      title: 'Execution Oversight Retainer',
      tag: 'Higher-touch',
      summary: 'A retainer for repeat operators who need weekly oversight, better coordination, and tighter follow-through across larger or more active residential projects.',
      pain: 'Weak coordination and loose project structure are causing expensive slippage across active files.',
      outcome: 'Start with a retainer review so recurring oversight support matches the project load and control needs.',
      details: ['Weekly oversight touchpoint', 'Up to 4 active project reviews each month, each covering 1 project status review with milestone, risk, and next-step guidance', 'Budget and scope review support', 'Milestone and risk summaries'],
      included: ['Retainer framework', 'Weekly touchpoint', 'Defined support cap'],
      notIncluded: ['Unlimited project support', 'Open-ended field management'],
      fit: 'Best when active files need higher-touch recurring oversight.',
      purchaseType: 'recurring',
      primaryAction: 'plan',
      cta: 'Request Retainer Review',
      detailHref: detailHref('developers-landowners', 'execution-oversight-retainer'),
      ctaHref: '/recurring-support#developers',
      monthlyPrice: 'Starting at $3,500/mo',
      monthlyLimit: 'Defined project cap, meetings and site visits scoped separately',
      turnaround: 'Priority 24-hour response target',
      proofTitle: 'Useful when oversight needs to be higher-touch',
      proofBody: 'This should begin with review, not checkout.',
      why: 'Higher-touch recurring scope depends on live-file complexity.',
    },
  ],
};

export const avatarPages: AvatarPageData[] = [
  homeownerServices,
  investorServices,
  realtorServices,
  contractorServices,
  developerServices,
];

export const avatarOverviewCards = avatarPages.map((page) => ({
  href: `/services/${page.slug}`,
  eyebrow: page.eyebrow,
  title: page.heroTitle,
  pain: page.painPoints[0],
  outcome: page.outcomes[0],
  cta: `See ${page.eyebrow} Services`,
}));

export function getAvatarPage(slug: string) {
  return avatarPages.find((page) => page.slug === slug);
}

export function getAllServices() {
  return avatarPages.flatMap((page) => [
    ...(page.fixed || []).map((service) => ({ ...service, avatar: page.slug, avatarLabel: page.eyebrow })),
    ...(page.priced || []).map((service) => ({ ...service, avatar: page.slug, avatarLabel: page.eyebrow })),
    ...(page.review || []).map((service) => ({ ...service, avatar: page.slug, avatarLabel: page.eyebrow })),
    ...(page.recurring || []).map((service) => ({ ...service, avatar: page.slug, avatarLabel: page.eyebrow })),
  ]);
}

export function getServiceBySlug(avatarSlug: string, serviceSlug: string) {
  const avatar = getAvatarPage(avatarSlug);
  if (!avatar) return null;

  const services = [...(avatar.fixed || []), ...(avatar.priced || []), ...(avatar.review || []), ...(avatar.recurring || [])];
  return services.find((service) => service.slug === serviceSlug) || null;
}
