#!/usr/bin/env python3
"""
build_subcontractors_import.py

Reads the 119-sub crown-jewel SQLite directory
(business-relationships/subcontractors.db) and emits paste-ready SQL that
upserts those subs into the public.subcontractors master table.

Apply subcontractors_master.sql FIRST, then paste the generated
subcontractors_import.sql into the Supabase SQL editor.

Mapping is best-effort:
  - raw trade   -> canonical COMMON_TRADES (source_trade preserves the original)
  - service_area free-text -> canonical NC_REGIONS[] (source_service_area preserves raw)
Rows with no region match get regions = NULL and a note; refine later in VendorBoard.
Sourced subs land as source='sourced-import', status='new', unvetted.
"""

import sqlite3
import os

HERE = os.path.dirname(os.path.abspath(__file__))
SRC_DB = os.path.normpath(os.path.join(HERE, "..", "..", "business-relationships", "subcontractors.db"))
OUT_SQL = os.path.normpath(os.path.join(HERE, "..", "supabase", "subcontractors_import.sql"))

# raw 119-db trade -> canonical COMMON_TRADES
TRADE_MAP = {
    "Architect": "Other",
    "Cabinetry": "Kitchen & Bath / Cabinetry",
    "Electrician": "Electrical",
    "Framer": "General / Framing",
    "HVAC": "Mechanical / HVAC",
    "Painter": "Drywall / Painting",
    "Plumber": "Plumbing",
    "Roofer": "Roofing",
    "Siding & Windows": "Siding / Exterior",
    "Surveyor": "Other",
    "Tile": "Tile / Stone",
    "TBD": "Other",
}

# canonical NC_REGIONS
R_CHAR = "Charlotte Metro"
R_TRI  = "Triangle (Raleigh–Durham)"
R_TRIAD = "Triad (Greensboro–Winston-Salem)"
R_FAY  = "Fayetteville / Sandhills"
R_WILM = "Wilmington / Coastal"
R_EAST = "Eastern NC"
R_WEST = "Western NC (Asheville)"
ALL_REGIONS = [R_CHAR, R_TRI, R_TRIAD, R_FAY, R_WILM, R_EAST, R_WEST]

# keyword -> region (checked against lowercased service_area). Order matters:
# 'greenville sc' is South Carolina and must NOT map to NC Eastern.
def map_regions(service_area: str):
    if not service_area:
        return []
    s = service_area.lower()
    regions = set()

    if any(k in s for k in ["statewide", "north carolina wide", "nc wide", "raleigh and statewide", "statewide nc"]):
        return list(ALL_REGIONS)

    # Charlotte + western-piedmont (Unifour) grouped to nearest major metro
    if any(k in s for k in ["charlotte", "gastonia", "concord", "statesville", "mooresville",
                            "hickory", "lenoir", "morganton", "conover", "granite falls", "newton"]):
        regions.add(R_CHAR)
    if any(k in s for k in ["raleigh", "durham", "chapel hill", "cary", "wake", "rtp",
                            "triangle", "piedmont", "apex", "wake forest"]):
        regions.add(R_TRI)
    if any(k in s for k in ["greensboro", "winston", "triad", "high point"]):
        regions.add(R_TRIAD)
    if any(k in s for k in ["fayetteville", "sandhills", "pinehurst", "southern pines"]):
        regions.add(R_FAY)
    if any(k in s for k in ["wilmington", "coastal"]):
        regions.add(R_WILM)
    # Eastern NC (incl. NE coastal Currituck/Elizabeth City, Pitt/Greenville-NC, New Bern)
    # Guard: strip 'greenville sc' / 'greenville, sc' so SC does not trigger Eastern.
    s_nc = s.replace("greenville sc", "").replace("greenville, sc", "").replace("greenville, greenville sc", "")
    if any(k in s_nc for k in ["greenville", "new bern", "elizabeth city", "pitt", "pamlico",
                               "washington", "kinston", "wilson", "farmville", "winterville",
                               "currituck", "coinjock", "eastern nc", "northeastern"]):
        regions.add(R_EAST)
    if any(k in s for k in ["asheville", "wnc", "western nc", "mountains"]):
        regions.add(R_WEST)

    return list(regions)


def sql_str(v):
    if v is None or (isinstance(v, str) and v.strip() == ""):
        return "NULL"
    return "'" + str(v).replace("'", "''") + "'"


def sql_text_array(items):
    if not items:
        return "NULL"
    inner = ", ".join("'" + i.replace("'", "''") + "'" for i in items)
    return f"ARRAY[{inner}]::text[]"


def main():
    con = sqlite3.connect(SRC_DB)
    con.row_factory = sqlite3.Row
    rows = con.execute(
        "SELECT company_name, contact_name, trade, phone, email, website, "
        "service_area, city, specialties, license_number, notes FROM subcontractors"
    ).fetchall()
    con.close()

    lines = []
    lines.append("-- Generated by build_subcontractors_import.py — 119-sub seed for public.subcontractors")
    lines.append("-- Apply subcontractors_master.sql FIRST. Idempotent via ON CONFLICT (lower(company_name), trade).")
    lines.append("")
    unmapped_region = 0

    for r in rows:
        raw_trade = (r["trade"] or "").strip()
        canon_trade = TRADE_MAP.get(raw_trade, "Other")
        regions = map_regions(r["service_area"] or "")
        if not regions:
            unmapped_region += 1
        note_bits = []
        if r["notes"]:
            note_bits.append(str(r["notes"]))
        if raw_trade in ("Architect", "Surveyor", "TBD"):
            note_bits.append(f"[source trade: {raw_trade} — mapped to Other; reclassify]")
        if not regions:
            note_bits.append("[region unmapped — set NC_REGIONS in VendorBoard]")
        note = " ".join(note_bits) if note_bits else None

        vals = [
            sql_str(r["company_name"]),
            sql_str(r["contact_name"]),
            sql_str(r["email"]),
            sql_str(r["phone"]),
            sql_str(r["website"]),
            sql_str(canon_trade),
            sql_str(raw_trade),
            sql_str(r["specialties"]),
            sql_text_array(regions),
            sql_str(r["service_area"]),
            sql_str(r["city"]),
            sql_str(r["license_number"]),
            sql_str(note),
        ]
        lines.append(
            "insert into public.subcontractors "
            "(company_name, contact_name, email, phone, website, trade, source_trade, "
            "specialties, regions, source_service_area, home_base_city, license_number, notes, "
            "source, status, license_verified, availability_status) values ("
            + ", ".join(vals)
            + ", 'sourced-import', 'new', false, 'unknown') "
            "on conflict (lower(company_name), trade) do nothing;"
        )

    lines.append("")
    lines.append(f"-- {len(rows)} rows; {unmapped_region} with no region match (flagged in notes).")

    with open(OUT_SQL, "w") as f:
        f.write("\n".join(lines) + "\n")

    print(f"Wrote {OUT_SQL}")
    print(f"{len(rows)} subs; {unmapped_region} with unmapped region.")


if __name__ == "__main__":
    main()
