export type InvestorActionRoute = {
  slug: string;
  title: string;
  eyebrow: string;
  summary: string;
  cta: string;
  mode: 'pricing' | 'quote' | 'subscribe';
  priceLabel: string;
  bullets: string[];
  fit: string;
  nextStep: string;
};

export const investorActionRoutes: InvestorActionRoute[] = [
  {
    slug: 'contractor-match-bid-coordination',
    title: 'Contractor Match + Bid Coordination',
    eyebrow: 'Investor Pricing Review',
    summary: 'Get cleaner contractor targeting, bid coordination, and proposal comparison before startup decisions get expensive.',
    cta: 'Start Pricing Review',
    mode: 'pricing',
    priceLabel: 'Starts at $1,499 per project',
    bullets: ['Project review for bid targeting', 'Contractor-fit targeting', 'Bid intake and comparison', 'Gap and risk notes'],
    fit: 'Best when you need more than random bids and want a cleaner way to compare contractors before startup.',
    nextStep: 'Send the project details, current scope, and any contractor information so Southern Cities can size the support correctly.',
  },
  {
    slug: 'full-due-diligence-package',
    title: 'Full Due Diligence Package',
    eyebrow: 'Investor Quote Review',
    summary: 'One packaged path covering deal review, permit risk, budget pressure-testing, and contractor decision support before you commit.',
    cta: 'Request Quote Review',
    mode: 'quote',
    priceLabel: 'Custom packaged scope',
    bullets: ['Deal and scope review', 'Permit and compliance risk notes', 'Budget direction support', 'Contractor decision guidance'],
    fit: 'Best when one decision package needs to cover the whole front-end construction risk picture.',
    nextStep: 'Share the address, scope, timing, and decision deadline so Southern Cities can scope the package and quote path.',
  },
  {
    slug: 'project-timeline-schedule-preparation',
    title: 'Project Timeline & Schedule Preparation',
    eyebrow: 'Investor Pricing Review',
    summary: 'Build a more defensible timeline before lenders, partners, or contractors are working off the wrong schedule.',
    cta: 'Start Pricing Review',
    mode: 'pricing',
    priceLabel: 'Project-specific pricing',
    bullets: ['Schedule structure review', 'Milestone sequencing', 'Timeline pressure points', 'Recommended next-step plan'],
    fit: 'Best when the schedule needs to hold up under lender, partner, or startup pressure.',
    nextStep: 'Send the scope, timeline target, and any existing schedule assumptions for review.',
  },
  {
    slug: 'schedule-of-cashflows-preparation',
    title: 'Schedule of Cashflows Preparation',
    eyebrow: 'Investor Pricing Review',
    summary: 'Build a cleaner cashflow schedule before work starts so funding timing and construction timing stay aligned.',
    cta: 'Start Pricing Review',
    mode: 'pricing',
    priceLabel: 'Project-specific pricing',
    bullets: ['Cashflow timing review', 'Construction-phase sequencing', 'Funding pressure points', 'Recommended next-step plan'],
    fit: 'Best when cash timing mistakes would create preventable lender or liquidity pressure.',
    nextStep: 'Send the scope, timeline, and draw or funding assumptions for review.',
  },
  {
    slug: 'material-logistics-setup',
    title: 'Material Logistics Setup',
    eyebrow: 'Investor Pricing Review',
    summary: 'Set up vendor, sourcing, and delivery logic before material delays start compounding project drag.',
    cta: 'Start Pricing Review',
    mode: 'pricing',
    priceLabel: 'Project-specific pricing',
    bullets: ['Material sourcing review', 'Delivery sequencing', 'Vendor setup guidance', 'Logistics risk notes'],
    fit: 'Best when startup coordination needs to be cleaner before crews are ready to move.',
    nextStep: 'Send the scope, material concerns, and startup timeline so Southern Cities can size the setup work.',
  },
  {
    slug: 'permit-coordination-administration',
    title: 'Permit Coordination & Administration',
    eyebrow: 'Investor Pricing Review',
    summary: 'Permit handling support for investors who need filings, follow-up, corrections, and inspections pushed forward more cleanly.',
    cta: 'Start Pricing Review',
    mode: 'pricing',
    priceLabel: 'Starts at $899 per permit',
    bullets: ['Permit file review', 'Submission coordination', 'Correction handling', 'Inspection scheduling support'],
    fit: 'Best when the permit side is slowing startup or creating avoidable drag.',
    nextStep: 'Send the jurisdiction, permit status, and project timeline so Southern Cities can scope the support correctly.',
  },
  {
    slug: 'lender-ready-scope-bid-package',
    title: 'Lender-Ready Scope & Bid Package',
    eyebrow: 'Investor Pricing Review',
    summary: 'Build cleaner lender-facing scope and bid support before funding conversations get stalled by weak backup.',
    cta: 'Start Pricing Review',
    mode: 'pricing',
    priceLabel: 'Scope-dependent pricing',
    bullets: ['Lender-facing scope review', 'Bid package cleanup', 'Gap notes', 'Submission-readiness guidance'],
    fit: 'Best when lender friction is coming from weak scope clarity or weak supporting backup.',
    nextStep: 'Send the lender requirements, current scope, bids, and timeline for review.',
  },
  {
    slug: 'construction-draw-strategy-alignment',
    title: 'Construction Draw Strategy & Alignment',
    eyebrow: 'Investor Pricing Review',
    summary: 'Lock in a cleaner draw strategy before the lender sets expectations around the wrong sequence or wrong support.',
    cta: 'Start Pricing Review',
    mode: 'pricing',
    priceLabel: 'Project-specific pricing',
    bullets: ['Draw sequencing review', 'Support-gap review', 'Funding pressure points', 'Recommended next-step plan'],
    fit: 'Best when draw timing and lender expectations need to be cleaner before the project gets further along.',
    nextStep: 'Send the budget, draw expectations, and lender process details for review.',
  },
  {
    slug: 'owner-controlled-construction-gc-led',
    title: 'Owner-Controlled Construction, GC-Led',
    eyebrow: 'Investor Quote Review',
    summary: 'Licensed GC execution for investors who want Southern Cities running the project while they stay in the owner seat.',
    cta: 'Request Quote Review',
    mode: 'quote',
    priceLabel: '8% to 15% of construction cost, project-dependent',
    bullets: ['Project review', 'Execution structure discussion', 'GC scope alignment', 'Next-step recommendation'],
    fit: 'Best when the project needs licensed execution-grade control, not just one support piece.',
    nextStep: 'Send the address, scope, timeline, and ownership structure so Southern Cities can review the fit and quote path.',
  },
  {
    slug: 'full-construction-management-service',
    title: 'Full Construction Management Service',
    eyebrow: 'Investor Quote Review',
    summary: 'Higher-touch project management support for investors who need the job carried from kickoff through closeout.',
    cta: 'Request Quote Review',
    mode: 'quote',
    priceLabel: '12% to 18% of total project cost',
    bullets: ['Project review', 'Management-scope discussion', 'Control and coordination needs', 'Next-step recommendation'],
    fit: 'Best when the owner does not want to personally carry active construction management burden.',
    nextStep: 'Send the project scope, active status, and management expectations so Southern Cities can review the quote path.',
  },
  {
    slug: 'regional-investor-construction-network-development',
    title: 'Regional Investor Construction Network Development',
    eyebrow: 'Investor Quote Review',
    summary: 'Build a repeatable regional construction operating layer before scale starts outrunning your current vendor and support setup.',
    cta: 'Request Quote Review',
    mode: 'quote',
    priceLabel: '$7,500 setup + $1,499/month operating retainer',
    bullets: ['Target-market review', 'Vendor/network setup discussion', 'Operating-model fit review', 'Next-step recommendation'],
    fit: 'Best when you are building repeatable infrastructure, not solving one isolated project problem.',
    nextStep: 'Send the target market, current operation, and scaling goals so Southern Cities can scope the buildout.',
  },
  {
    slug: 'project-coordination-control',
    title: 'Project Coordination & Control',
    eyebrow: 'Investor Support Plan',
    summary: 'Monthly coordination support for active investor projects that need tighter follow-through without full project management.',
    cta: 'Review Support Plan',
    mode: 'subscribe',
    priceLabel: '$1,499/month per active project',
    bullets: ['Active-job coordination review', 'Milestone structure', 'Follow-through support', 'Recommended next-step plan'],
    fit: 'Best when active jobs need steadier control but not a full management takeover.',
    nextStep: 'Review the fit and expected support load before monthly support starts.',
  },
  {
    slug: 'investor-operator-support',
    title: 'Investor Operator Support',
    eyebrow: 'Investor Support Plan',
    summary: 'Monthly construction-side support across repeated investor files when the same decisions keep coming back.',
    cta: 'Review Support Plan',
    mode: 'subscribe',
    priceLabel: '$1,799 / $2,999 / $4,999 per month',
    bullets: ['Recurring deal support', 'Construction-side decision help', 'Repeat-file support capacity', 'Recommended next-step plan'],
    fit: 'Best when repeated deal friction is consuming too much owner time every month.',
    nextStep: 'Review the monthly support fit and support volume before starting a plan.',
  },
  {
    slug: 'due-diligence-package-3-deals-month',
    title: 'Due Diligence Package, 3 deals/month',
    eyebrow: 'Investor Support Plan',
    summary: 'Packaged recurring diligence support for operators who need a faster, repeatable front-end review rhythm.',
    cta: 'Review Support Plan',
    mode: 'subscribe',
    priceLabel: '$2,499/month',
    bullets: ['Recurring deal review capacity', 'Scope and risk notes', 'Decision support rhythm', 'Recommended next-step plan'],
    fit: 'Best when the same diligence workload repeats often enough to justify a packaged monthly structure.',
    nextStep: 'Review the monthly fit, expected deal count, and support cadence before starting.',
  },
  {
    slug: 'construction-planning-package-3-deals-month',
    title: 'Construction Planning Package, 3 deals/month',
    eyebrow: 'Investor Support Plan',
    summary: 'Monthly planning support for operators launching multiple files and needing repeatable startup coordination.',
    cta: 'Review Support Plan',
    mode: 'subscribe',
    priceLabel: '$2,999/month',
    bullets: ['Recurring startup planning support', 'Scope and sequencing help', 'Permit and lender readiness notes', 'Recommended next-step plan'],
    fit: 'Best when project startup work keeps repeating and needs a steadier planning structure.',
    nextStep: 'Review the expected monthly project load and support mix before starting.',
  },
];
